### ISSUE TITLE
pulumi up plan creation error: "Resource group '{resourceGroupName}' could not be found."

### ISSUE THREAD

**Issue by simra** [pulumi/pulumi-azure#1171]
### What happened?

When I build a stack from scratch, I receive the stack trace below.  It looks like storage.list_storage_keys is attempting to poll for a resource group before it's even created.  Note the template placeholder {resourceGroupName} in the error message returned by Azure.  

I can work around the issue if I build the stack in two stages, adding an exit() before this call, building the stack, and then removing it to continue the build, but this is pretty tedious.
```

Diagnostics:
  pulumi:pulumi:Stack (infrastructure-prod):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/simra/t4t-infrastructure/infrastructure/./__main__.py", line 217, in <module>
        img_storage_account_access_keys = storage.list_storage_account_keys(
      File "/home/simra/t4t-infrastructure/infrastructure/venv/lib/python3.8/site-packages/pulumi_azure_native/storage/list_storage_account_keys.py", line 66, in list_storage_account_keys
        __ret__ = pulumi.runtime.invoke('azure-native:storage:listStorageAccountKeys', __args__, opts=opts, typ=ListStorageAccountKeysResult).value
      File "/home/simra/t4t-infrastructure/infrastructure/venv/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 144, in invoke
        raise invoke_error
    Exception: invoke of azure-native:storage:listStorageAccountKeys failed: invocation of azure-native:storage:listStorageAccountKeys returned an error: request failed /subscriptions/b1906ec2-cd64-4241-82ad-28f55b731ffd/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts/{accountName}/listKeys: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group '{resourceGroupName}' could not be found."
```

### Steps to reproduce

Here's a minimal version of my __main__.py:

https://gist.github.com/simra/1640390a23a93edfcd3659670fed8058

### Expected Behavior

Expect pulumi to build a plan without requiring an existing resource group.

### Actual Behavior

It errors out as shown above.

### Output of `pulumi about`

$ pulumi about
CLI
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.87.0
python        unknown
random        4.8.0

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='/home/simra/t4t-infrastructure/infrastructure/venv/bin/python3' version='3.8.12
'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/simra
User           simra
Organizations  simra, tech4tracing

Dependencies:
NAME                 VERSION
pip                  22.3.1
pulumi-azure-native  1.87.0
pulumi-random        4.8.0
setuptools           65.5.1
wheel                0.38.4

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Unfortunately this is a tricky part of the intended behaviour of invokes (functions) compared to resources - they are executed at preview time. 

In your example provided, you should be able to work around this by restructuring your code along the lines of:

```python
img_storage_account_access_keys = img_storage_account.name.apply(
    lambda args: storage.list_storage_account_keys(
        account_name=img_storage_account.name,
        resource_group_name=resource_group.name
    ).keys[0]['value']
)
img_storage_account_connection_string = pulumi.Output.all(
    img_storage_account.name, img_storage_account_access_keys
).apply(
    lambda args: f"DefaultEndpointsProtocol=https;AccountName={args[0]};AccountKey={args[1]};EndpointSuffix=core.windows.net"
)
```

Doing the lookup inside the apply should mean it won't execute until the name is known.

Another workaround is to use the following helper to change behaviour during a preview: `pulumi.runtime.is_dry_run()`
