### ISSUE TITLE
Panic in Terraform Provider creating a CosmosDB account with multiple geoLocations

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-azure#119]
```ts
Diagnostics:
  pulumi:pulumi:Stack: <redacted>
    info: panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x26d03bf]
    goroutine 342 [running]:
    github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmCosmosDBAccountRead(0xc420a6c070, 0x2d24da0, 0xc420710000, 0xc420570460, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_cosmos_db_account.go:555 +0x180f
    github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmCosmosDBAccountCreate(0xc420a6c070, 0x2d24da0, 0xc420710000, 0xc420a6c070, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_cosmos_db_account.go:354 +0xdcb
    github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc420437110, 0xc420ac9450, 0xc4205274c0, 0x2d24da0, 0xc420710000, 0xc420527401, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x364
    github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc420477ce0, 0xc420a59600, 0xc420ac9450, 0xc4205274c0, 0xc4205274c0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc4205ab590, 0x3dcf920, 0xc420920840, 0xc420b88540, 0xc4205ab590, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:469 +0x542
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x3dcf920, 0xc420920840, 0x2c4f320, 0xc420b88540, 0x3dcf920, 0xc420920840, 0x3dd5e20, 0x3e747f0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1229 +0x86
    github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3dcf920, 0xc420920840, 0x2c4f320, 0xc420b88540, 0xc42052d620, 0xc42052d640, 0x0, 0x0, 0x3dbcd20, 0xc42021fbe0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x2cf1a20, 0xc4205ab590, 0x3dcf920, 0xc420ec8930, 0xc420ac9400, 0xc420283800, 0x0, 0x0, 0xc420969ac0, 0xc420969ac8)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1231 +0x16d
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200c8000, 0x3dd45c0, 0xc420088000, 0xc42091a200, 0xc4204cb7d0, 0x3e48620, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:826 +0xab4
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200c8000, 0x3dd45c0, 0xc420088000, 0xc42091a200, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:1023 +0x1528
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42043a120, 0xc4200c8000, 0x3dd45c0, 0xc420088000, 0xc42091a200)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:570 +0xa1

  azure:containerservice:KubernetesCluster: aks-aks
    error: Plan apply failed: transport is closing

  azure:cosmosdb:Account: cosmosdb
    error: Plan apply failed: transport is closing

info: 25 changes performed:
    + 25 resources created
Update duration: 11m59.302509812s
```

**Comment by joeduffy** [comment]
This doesn't appear to repro any longer. This program provisioned happily:

```python
import pulumi
from pulumi_azure import core, cosmosdb

# Create an Azure Resource Group
rg = core.ResourceGroup('myrg', location='WestUS')

# Create an Azure CosmosDB instance.
db = cosmosdb.Account('db',
    location=rg.location,
    resource_group_name=rg.name,
    consistency_policy={
        'consistency_level': 'BoundedStaleness',
        'max_interval_in_seconds': 10,
        'max_staleness_prefix': 200,
    },
    enable_automatic_failover=True,
    geo_locations=[
        {
            'failover_priority': 1,
            'location': 'EastUS',
        },
        {
            'failover_priority': 0,
            'location': rg.location,
        }
    ],
    kind='GlobalDocumentDB',
    offer_type='Standard'
)

pulumi.export('cosmosdb_endpoint', db.endpoint)
```
