### ISSUE TITLE
Keyvault (AccessPolicy?) usage in 16.8 or 16.9 causes panic

### ISSUE THREAD

**Issue by dbilleci-lightstream** [pulumi/pulumi-azure#183]
I ran into this same issue with both 16.8 and 16.9 of the provider.  I'm not exactly sure what is the cause, but I just re-ran a few tests and I hit the error when I tried this:

Existing (before):
````
        let vault_access_policy = new azure.keyvault.AccessPolicy(vault_access_policy_name, {
            vaultName: vault_name_parsed,
            resourceGroupName: vault_resource_group_name,
            tenantId: String(azure_config.tenantId),
            objectId: uai.principalId,
            keyPermissions: ['get', 'list'],
            certificatePermissions: ['get', 'list'],
            secretPermissions: ['get', 'list']
        })
````

Then changed to:
````
        let vault_access_policy = new azure.keyvault.AccessPolicy(vault_access_policy_name, {
            keyVaultId: AzureUtils.get_keyvault_id(env_id, region, vault.name, config.get('resource_prefix')),
            tenantId: String(azure_config.tenantId),
            objectId: uai.principalId,
            keyPermissions: ['get', 'list'],
            certificatePermissions: ['get', 'list'],
            secretPermissions: ['get', 'list']
        })
````

With running 16.9:
````
    root@243674c272cf:/data/pulumi/infra/azure/core-msi# pulumi plugin ls
    NAME   KIND      VERSION  SIZE    INSTALLED  LAST USED
    aws    resource  0.16.8   155 MB  n/a        51 minutes ago
    azure  resource  0.16.9   90 MB   n/a        51 minutes ago
    
    TOTAL plugin cache size: 245 MB
````

And I get this (whole lotta muck):
https://pastebin.com/2Sakd5UP

**Comment by jen20** [comment]
Hi @dbilleci-lightstream! Thanks for the detailed repro, I’ll take a look into this and see what we can do.

**Comment by jen20** [comment]
I've been attempting to reproduce this locally, and can't get it to happen with _just_ the latest provider. My guess is that it requires the resources to have been created the using 0.16.7, and then the provider upgraded to a later version.

The program I'm using is:

```typescript
import * as azure from "@pulumi/azure";

const resourceGroup = new azure.core.ResourceGroup("resourceGroup", {
    location: "WestUS",
});

const vault = new azure.keyvault.KeyVault("vault", {
    name: "repro183vault",

    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,

    tenantId: <string>azure.config.tenantId,

    sku: {
        name: "standard",
    },

    networkAcls: {
        defaultAction: "Deny",
        bypass: "AzureServices",
    },

    tags: {
        Purpose: "Repro azure#183"
    },
});

const vaultAccessPolicy = new azure.keyvault.AccessPolicy("policy", {
    keyVaultId: vault.id,
    tenantId: <string>azure.config.tenantId,
    objectId: "xxxx", // redacted, my user's object ID
    keyPermissions: ['get', 'list'],
    certificatePermissions: ['get', 'list'],
    secretPermissions: ['get', 'list']
});
```

The output from `pulumi plugin ls` (apologies, I have a lot...):

```
 ▲ Code/pulumi-repro/azure-183 pulumi plugin ls
NAME        KIND      VERSION                          SIZE    INSTALLED     LAST USED
aws         resource  0.16.8                           154 MB  6 days ago    now
aws         resource  0.16.7                           143 MB  2 weeks ago   now
aws         resource  0.16.5                           138 MB  1 month ago   now
aws         resource  0.16.4-dev.1544849085+gfa42da3b  135 MB  2 months ago  now
aws         resource  0.16.3                           135 MB  2 months ago  now
azure       resource  0.16.9                           89 MB   1 hour ago    now
azure       resource  0.16.8                           89 MB   6 days ago    now
azure       resource  0.16.7                           88 MB   2 weeks ago   now
docker      resource  0.16.4                           34 MB   2 weeks ago   now
docker      resource  0.16.2                           34 MB   2 months ago  now
f5bigip     resource  0.1.2-dev.1549067585+g0637c1d    34 MB   6 days ago    now
gcp         resource  0.16.8                           61 MB   6 days ago    now
gcp         resource  0.16.4                           61 MB   1 month ago   now
kubernetes  resource  0.20.2                           45 MB   6 days ago    now
kubernetes  resource  0.18.0                           43 MB   1 month ago   now
openstack   resource  0.16.5-dev.1550091790+g35ebcbd   40 MB   6 days ago    now
packet      resource  0.1.0                            31 MB   6 days ago    now
random      resource  0.4.0                            28 MB   6 days ago    now
random      resource  0.2.0                            35 MB   1 month ago   now
vsphere     resource  0.16.4                           53 MB   6 days ago    now
```

And finally the output from `pulumi up`:

```
 ▲ Code/pulumi-repro/azure-183 pulumi up                                                                                                                                                                    1m
Previewing update (dev):

     Type                            Name           Plan
 +   pulumi:pulumi:Stack             azure-183-dev  create
 +   ├─ azure:core:ResourceGroup     resourceGroup  create
 +   ├─ azure:keyvault:KeyVault      vault          create
 +   └─ azure:keyvault:AccessPolicy  policy         create

Resources:
    + 4 to create

Do you want to perform this update? yes
Updating (dev):

     Type                            Name           Status
 +   pulumi:pulumi:Stack             azure-183-dev  created
 +   ├─ azure:core:ResourceGroup     resourceGroup  created
 +   ├─ azure:keyvault:KeyVault      vault          created
 +   └─ azure:keyvault:AccessPolicy  policy         created

Resources:
    + 4 created

Duration: 2m13s

Permalink: https://app.pulumi.com/jen20/azure-183/dev/updates/11
```

I'll try uninstalling the newer plugins and running through the same upgrade path.

**Comment by dbilleci-lightstream** [comment]
I think the part that triggered it for me was changing the 2 parameters in the access policy:

original with resourceGroup and vaultName params:
````
        let vault_access_policy = new azure.keyvault.AccessPolicy(vault_access_policy_name, {
            vaultName: vault_name_parsed,
            resourceGroupName: vault_resource_group_name,
````

But that gives a deprecation warning on > 16.7 now, so I had refactored it to use keyVaultId single param:
````
        let vault_access_policy = new azure.keyvault.AccessPolicy(vault_access_policy_name, {
            keyVaultId: AzureUtils.get_keyvault_id(env_id, region, vault.name, config.get('resource_prefix')),
````

**Comment by dbilleci-lightstream** [comment]
If you wanted to get really precise, it would be first creating it on 16.7 with `resourceGroup and vaultName` and then upgrading to 16.8 or 16.9 and then changing it to use the single `keyVaultId`

**Comment by jen20** [comment]
Hmm, I also can't reproduce it that way. Here are the steps I took, in case you can notice anything different, @dbilleci-lightstream:

Remove all the plugins, using `pulumi plugin rm --all` and confirming.

Start with the program in the pre-0.16.8 form, with a strict dependency on version 0.16.7 of `@pulumi/azure` in `package.json`:

```typescript
import * as azure from "@pulumi/azure";

const resourceGroup = new azure.core.ResourceGroup("resourceGroup", {
    location: "WestUS",
});

const vault = new azure.keyvault.KeyVault("vault", {
    name: "repro183vault",

    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,

    tenantId: <string>azure.config.tenantId,

    sku: {
        name: "standard",
    },

    networkAcls: {
        defaultAction: "Deny",
        bypass: "AzureServices",
    },

    tags: {
        Purpose: "Repro azure#183"
    },
});

const vaultAccessPolicy = new azure.keyvault.AccessPolicy("policy", {
    vaultName: vault.name,
    resourceGroupName: resourceGroup.name,
    tenantId: <string>azure.config.tenantId,
    objectId: "redacted", // my azure user object ID
    keyPermissions: ['get', 'list'],
    certificatePermissions: ['get', 'list'],
    secretPermissions: ['get', 'list']
});
```

Run the program, and see the resources created:

```
 ▲ Code/pulumi-repro/azure-183 npm install                                                                                                                                             21s  ⇡ master :: 8m :: ⬡

> @pulumi/azure@0.16.7 install /Users/James/Code/pulumi-repro/azure-183/node_modules/@pulumi/azure
> node scripts/install-pulumi-plugin.js resource azure v0.16.7

[resource plugin azure-0.16.7] installing
npm WARN azure-typescript@ No description
npm WARN azure-typescript@ No repository field.
npm WARN azure-typescript@ No license field.

updated 1 package and audited 498 packages in 2.491s
found 0 vulnerabilities


 ▲ Code/pulumi-repro/azure-183 pulumi plugin ls                                                                                                                                             ⇡ master :: 9m :: ⬡
NAME   KIND      VERSION  SIZE   INSTALLED      LAST USED
azure  resource  0.16.7   88 MB  2 minutes ago  4 seconds ago

TOTAL plugin cache size: 88 MB

 ▲ Code/pulumi-repro/azure-183 pulumi up                                                                                                                                                    ⇡ master :: 9m :: ⬡
Previewing update (dev):

     Type                            Name           Plan
 +   pulumi:pulumi:Stack             azure-183-dev  create
 +   ├─ azure:core:ResourceGroup     resourceGroup  create
 +   ├─ azure:keyvault:KeyVault      vault          create
 +   └─ azure:keyvault:AccessPolicy  policy         create

Resources:
    + 4 to create

Do you want to perform this update? details
+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:dev::azure-183::pulumi:pulumi:Stack::azure-183-dev]
    + azure:core/resourceGroup:ResourceGroup: (create)
        [urn=urn:pulumi:dev::azure-183::azure:core/resourceGroup:ResourceGroup::resourceGroup]
        location: "WestUS"
        name    : "resourcegroup00f05839"
    + azure:keyvault/keyVault:KeyVault: (create)
        [urn=urn:pulumi:dev::azure-183::azure:keyvault/keyVault:KeyVault::vault]
        location         : "WestUS"
        name             : "repro183vault"
        networkAcls      : {
            bypass       : "AzureServices"
            defaultAction: "Deny"
        }
        resourceGroupName: "resourcegroup00f05839"
        sku              : {
            name: "standard"
        }
        tags             : {
            Purpose: "Repro azure#183"
        }
        tenantId         : "25024bbc-53bb-4ccd-ab0c-26a4d95ccfd5"
    + azure:keyvault/accessPolicy:AccessPolicy: (create)
        [urn=urn:pulumi:dev::azure-183::azure:keyvault/accessPolicy:AccessPolicy::policy]
        certificatePermissions: [
            [0]: "get"
            [1]: "list"
        ]
        keyPermissions        : [
            [0]: "get"
            [1]: "list"
        ]
        objectId              : "79fdd019-87fd-4f1c-92bb-c931afa49370"
        resourceGroupName     : "resourcegroup00f05839"
        secretPermissions     : [
            [0]: "get"
            [1]: "list"
        ]
        tenantId              : "25024bbc-53bb-4ccd-ab0c-26a4d95ccfd5"
        vaultName             : "repro183vault"

Do you want to perform this update? yes
Updating (dev):

     Type                            Name           Status
 +   pulumi:pulumi:Stack             azure-183-dev  created
 +   ├─ azure:core:ResourceGroup     resourceGroup  created
 +   ├─ azure:keyvault:KeyVault      vault          created
 +   └─ azure:keyvault:AccessPolicy  policy         created

Resources:
    + 4 created

Duration: 2m15s

Permalink: https://app.pulumi.com/jen20/azure-183/dev/updates/13
```

Then, update `package.json` to refer to `latest` (which at the time of writing is 0.16.9), and `npm install` again, resulting in `pulumi plugin install resource azure 0.16.9` being executed:

```
 ▲ Code/pulumi-repro/azure-183 npm install                                                                                                                                                 ⇡ master :: 12m :: ⬡

> @pulumi/azure@0.16.9 install /Users/James/Code/pulumi-repro/azure-183/node_modules/@pulumi/azure
> node scripts/install-pulumi-plugin.js resource azure v0.16.9

[resource plugin azure-0.16.9] installing
Downloading plugin:  26.55 MiB / 26.55 MiB [========================] 100.00% 4s
npm WARN azure-typescript@ No description
npm WARN azure-typescript@ No repository field.
npm WARN azure-typescript@ No license field.

updated 1 package and audited 498 packages in 6.867s
found 0 vulnerabilities
```

Run `pulumi update`, and see the expected deprecation warning:

```
 ▲ Code/pulumi-repro/azure-183 pulumi up                                                                                                                                               8s  ⇡ master :: 12m :: ⬡
Previewing update (dev):

     Type                            Name           Plan     Info
     pulumi:pulumi:Stack             azure-183-dev
     └─ azure:keyvault:AccessPolicy  policy                  2 warnings

Diagnostics:
  azure:keyvault:AccessPolicy (policy):
    warning: urn:pulumi:dev::azure-183::azure:keyvault/accessPolicy:AccessPolicy::policy verification warning: "vault_name": [DEPRECATED] This property has been deprecated in favour of the key_vault_id property. This will prevent a class of bugs as described in https://github.com/terraform-providers/terraform-provider-azurerm/issues/2396 and will be removed in version 2.0 of the provider
    warning: urn:pulumi:dev::azure-183::azure:keyvault/accessPolicy:AccessPolicy::policy verification warning: "resource_group_name": [DEPRECATED] This property has been deprecated as the resource group is now pulled from the vault ID and will be removed in version 2.0 of the provider
```

Modify the program such that the `vaultAccessPolicy` resource is defined like this:

```typescript
const vaultAccessPolicy = new azure.keyvault.AccessPolicy("policy", {
    keyVaultId: vault.id,
    tenantId: <string>azure.config.tenantId,
    objectId: "redacted", // my azure user object ID
    keyPermissions: ['get', 'list'],
    certificatePermissions: ['get', 'list'],
    secretPermissions: ['get', 'list']
});
```

Finally, run `pulumi up` again, and see the expected modifications:

```
 ▲ Code/pulumi-repro/azure-183 pulumi up                                                                                                                                              18s  ⇡ master :: 13m :: ⬡
Previewing update (dev):

     Type                            Name           Plan        Info
     pulumi:pulumi:Stack             azure-183-dev
 +-  └─ azure:keyvault:AccessPolicy  policy         replace     [diff: +keyVaultId-resourceGroupName,vaultName]

Resources:
    +-1 to replace
    3 unchanged

Do you want to perform this update? yes
Updating (dev):

     Type                            Name           Status       Info
     pulumi:pulumi:Stack             azure-183-dev
 +-  └─ azure:keyvault:AccessPolicy  policy         replaced     [diff: +keyVaultId-resourceGroupName,vaultName]

Resources:
    +-1 replaced
    3 unchanged

Duration: 6s

Permalink: https://app.pulumi.com/jen20/azure-183/dev/updates/15
```

I'll keep digging here, but can you confirm whether that workflow matches the way you encountered this problem, @dbilleci-lightstream?

**Comment by jen20** [comment]
After some more back-and-forth with @dbilleci-lightstream on the community slack, we came to the conclusion that the reported panic is the failure mode when the supplied `keyVaultId` is not valid. It can be reproduced with the following program, at version 0.16.9 of the Azure resource provider:

```typescript
import * as azure from "@pulumi/azure";

const resourceGroup = new azure.core.ResourceGroup("resourceGroup", {
    location: "WestUS",
});

const vault = new azure.keyvault.KeyVault("vault", {
    name: "repro183vault",

    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,

    tenantId: <string>azure.config.tenantId,

    sku: {
        name: "standard",
    },

    networkAcls: {
        defaultAction: "Deny",
        bypass: "AzureServices",
    },

    tags: {
        Purpose: "Repro azure#183"
    },

});

const vaultAccessPolicy = new azure.keyvault.AccessPolicy("policy", {
    keyVaultId: vault.id.apply(x => `${x}nope`),
    tenantId: <string>azure.config.tenantId,
    objectId: "redacted", // my user object ID
    keyPermissions: ['get', 'list'],
    certificatePermissions: ['get', 'list'],
    secretPermissions: ['get', 'list']
});
```

On `pulumi up`:

```
 ▲ Code/pulumi-repro/azure-183 pulumi up                                                                                                                                                    ⇡ master :: 1h :: ⬡
Previewing update (dev):

     Type                            Name           Plan        Info
     pulumi:pulumi:Stack             azure-183-dev
 +-  └─ azure:keyvault:AccessPolicy  policy         replace     [diff: ~keyVaultId]

Resources:
    +-1 to replace
    3 unchanged

Do you want to perform this update? yes
Updating (dev):

     Type                            Name           Status                   Info
     pulumi:pulumi:Stack             azure-183-dev                           	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:566 +0     Type                            Name           Status                   Info
     pulumi:pulumi:Stack             azure-183-dev                           22 messages
 +-  └─ azure:keyvault:AccessPolicy  policy         **replacing failed**     [diff: ~keyVaultId]; 1 error

Diagnostics:
  azure:keyvault:AccessPolicy (policy):
    error: Plan apply failed: transport is closing

  pulumi:pulumi:Stack (azure-183-dev):
    panic: fatal: An assertion has failed: expected non-nil error with nil state during Create
    goroutine 117 [running]:
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc0007ce050, 0x4c)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc000685300, 0x33b8791, 0x33, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x126
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc000696e10, 0x3713fc0, 0xc000ae6720, 0xc000b141c0, 0xc000696e10, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:566 +0xbda
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x3713fc0, 0xc000ae6720, 0x3225660, 0xc000b141c0, 0x3713fc0, 0xc000ae6720, 0x372d220, 0x50acde0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1229 +0x86
    github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3713fc0, 0xc000ae6720, 0x3225660, 0xc000b141c0, 0xc000bb0320, 0xc000bb0340, 0x0, 0x0, 0x36feea0, 0xc0002e0c00)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:57 +0x2b0
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x32bc200, 0xc000696e10, 0x3713fc0, 0xc000ae63c0, 0xc000be0140, 0xc00033ffe0, 0x0, 0x0, 0xc0013081e0, 0x1d5)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1231 +0x158
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000557080, 0x372aa00, 0xc000408c00, 0xc000af5a00, 0xc0006a75f0, 0x5080ae0, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:966 +0x4a2
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000557080, 0x372aa00, 0xc000408c00, 0xc000af5a00, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:1245 +0xd58
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00003e120, 0xc000557080, 0x372aa00, 0xc000408c00, 0xc000af5a00)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:685 +0x9f
    created by github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:683 +0xa1
```

Returning a nil state and a nil error sound suspicious upstream - I'll have a dig around there and see what I can find there next.

**Comment by jen20** [comment]
Additionally, we confirmed that @dbilleci-lightstream can make progress by correcting the helper function being used to calculate the vault ID from components.

**Comment by dbilleci-lightstream** [comment]
@jen20 thanks again for spending the time to debug this! I've been able to move forward on my end with a stupid simple variable update.. I'll continue to follow the ticket for info on the (upstream?) issue.

**Comment by jen20** [comment]
So, this is a bug upstream. I can reproduce what would cause us to fail in this manner by running this Terraform configuration:

```hcl
resource "azurerm_key_vault_access_policy" "policy" {
  # note this has to at least appear to be a valid URI to a vault
  key_vault_id = "/subscriptions/<redacted>/resourceGroups/resourcegroupcbbd350e/providers/Microsoft.KeyVault/vaults/repro183vaultnope"

  # these don't matter
  tenant_id = "00000000-0000-0000-0000-000000000000"
  object_id = "11111111-1111-1111-1111-111111111111"

  key_permissions = [
    "get",
  ]

  secret_permissions = [
    "get",
  ]
}
```

Running `terraform apply`, I see this:

```
$ terraform apply                                                                                                                                                ⇡ master :: 1h :: ⬡

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + azurerm_key_vault_access_policy.policy
      id:                   <computed>
      key_permissions.#:    "1"
      key_permissions.0:    "get"
      key_vault_id:         "/subscriptions/<redacted>/resourceGroups/resourcegroupcbbd350e/providers/Microsoft.KeyVault/vaults/repro183vaultnope"
      object_id:            "11111111-1111-1111-1111-111111111111"
      resource_group_name:  <computed>
      secret_permissions.#: "1"
      secret_permissions.0: "get"
      tenant_id:            "00000000-0000-0000-0000-000000000000"
      vault_name:           <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_key_vault_access_policy.policy: Creating...
  key_permissions.#:    "" => "1"
  key_permissions.0:    "" => "get"
  key_vault_id:         "" => "/subscriptions/<redacted>/resourceGroups/resourcegroupcbbd350e/providers/Microsoft.KeyVault/vaults/repro183vaultnope"
  object_id:            "" => "11111111-1111-1111-1111-111111111111"
  resource_group_name:  "" => "<computed>"
  secret_permissions.#: "" => "1"
  secret_permissions.0: "" => "get"
  tenant_id:            "" => "00000000-0000-0000-0000-000000000000"
  vault_name:           "" => "<computed>"
azurerm_key_vault_access_policy.policy: Creation complete after 0s

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

However, no state is actually created:

```json
{
    "version": 3,
    "terraform_version": "0.11.11",
    "serial": 1,
    "lineage": "74a73fbb-d75a-af7a-c1dc-6d73cc1e9a73",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}
```

Our Terraform bridge asserts that this cannot happen, resulting in the panic we see as the presenting cause of this issue. The reason it fails is here (upstream):

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_key_vault_access_policy.go#L146-L152

Likely this was to automatically remove the policy of a removed vault, but results in returning a nil state and a nil error.

**Comment by jen20** [comment]
Actually, I think this is a straight up bug upstream, and that this error should instead be returned if the key vault is not found: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_key_vault_access_policy.go#L154

**Comment by jen20** [comment]
This has been fixed upstream now, in terraform-providers/terraform-provider-azurerm#2922 (in the exact form for this issue), and also in other resources susceptible to the same kind of failure (in terraform-providers/terraform-provider-azurerm#2923). It looks like they'll be in the 1.23.0 release upstream, so will get pulled in during the update when that is released.

Thanks for your patience in providing information when debugging this, @dbilleci-lightstream! I'll go ahead and close the issue as the fix will automatically be pulled in during the next update.
