### ISSUE TITLE
Bug in automatic location propagation for non-existing resource groups

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#239]
I think #216 doesn't fully work just yet.

Here is a simple repro:

``` ts
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";

const resourceGroup = new azure.core.ResourceGroup("test", { location: "WestUS" });

const sa = new azure.storage.Account("storage", {
    resourceGroupName: resourceGroup.name,
    accountReplicationType: "LRS",
    accountTier: "Standard"
});
```

If I run this on a clean stack, I get an error on preview:

```
    panic: interface conversion: interface {} is resource.Computed, not string
    goroutine 70 [running]:
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/resource.PropertyValue.StringValue(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/pkg/resource/properties.go:327
    github.com/pulumi/pulumi-azure.Provider.func1(0xc0007a8f60, 0xc000478ae0, 0x31ab6c8, 0x8, 0x60c1ba0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/resources.go:967 +0x565
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformInputs(0xc0007a8f60, 0xc000478ae0, 0xc000478b10, 0xc0006f4c90, 0xc00066dce0, 0xc000543780, 0xc0004892c0, 0x1, 0xc000713648, 0x47c902, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:184 +0xe9e
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Check(0xc000362b40, 0x375b660, 0xc000478a50, 0xc000bd1400, 0xc000362b40, 0x2d8fc01, 0xc000bd1440)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:451 +0x680
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler.func1(0x375b660, 0xc000478a50, 0x2fbb2a0, 0xc000bd1400, 0x300eae0, 0x60c05e0, 0x375b660, 0xc000478a50)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1295 +0x8d
    github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x375b660, 0xc000478900, 0x2fbb2a0, 0xc000bd1400, 0xc0007a8e00, 0xc0007a8e20, 0x0, 0x0, 0x36f19c0, 0xc0002bee90)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:57 +0x2eb
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler(0x3059300, 0xc000362b40, 0x375b660, 0xc000478900, 0xc000906dc0, 0xc00051cee0, 0x375b660, 0xc000478900, 0xc0000f2750, 0xc2)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1297 +0x15f
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004c4600, 0x379de80, 0xc0002aaa80, 0xc0007abf00, 0xc000488870, 0x6094c80, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:971 +0x477
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0004c4600, 0x379de80, 0xc0002aaa80, 0xc0007abf00, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:1250 +0xd2c
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002f0050, 0xc0004c4600, 0x379de80, 0xc0002aaa80, 0xc0007abf00)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:690 +0xa6
    created by github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:688 +0xa8

    error: transport is closing
```

**Workaround**:

I can make it work by first deploying the resource group without the storage account, and then deploying the storage account. If the resource group exists, location propagation works as advertised.

**Comment by mikhailshilkov** [comment]
tagging @joeduffy @jen20
