### ISSUE TITLE
package fails to install on windows

### ISSUE THREAD

**Issue by 4c74356b41** [pulumi/pulumi-azure#356]
```
> pip3 install pulumi-azure                                                                                             Collecting pulumi-azure
  Using cached https://files.pythonhosted.org/packages/8f/76/1cf9e1e4e1e8d13222a34034d388fcb03d4d973f46cc1249e4caa9bb6bbf/pulumi_azure-1.0.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\core\appdata\local\programs\python\python36-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\core\\AppData\\Local\\Temp\\pip-install-n1bhdol8\\pulumi-azure\\setup.py'"'"'; __file__='"'"'C:\\Users\\core\\AppData\\Local\\Temp\\pip-install-n1bhdol8\\pulumi-azure\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\core\AppData\Local\Temp\pip-install-n1bhdol8\pulumi-azure\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\core\AppData\Local\Temp\pip-install-n1bhdol8\pulumi-azure\setup.py", line 33, in <module>
        long_description=readme(),
      File "C:\Users\core\AppData\Local\Temp\pip-install-n1bhdol8\pulumi-azure\setup.py", line 28, in readme
        return f.read()
      File "c:\users\core\appdata\local\programs\python\python36-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 452: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

windows 10, pulumi 1.0, python 3.6.8. venv\no venv doesnt make a difference. works fine on linux

**Comment by ellismg** [comment]
Thanks!  I understand the issue here - we have smart quotes in our README.rst file and they are not being decoded correctly when trying to install the package (as it is not being opened as a UTF-8 file).  I'll have a quick fix for this shortly and then will be pushing out some larger changes to force us to always use UTF-8 encoding when opening the `README.rst`

**Comment by ellismg** [comment]
@4c74356b41 Could you try installing `pulumi-aws==1.0.1a1567796678` and see if this addresses the issue you're hitting?  If so, I will cut a `1.0.1` release of `pulumi-aws`.  Thanks!
