### ISSUE TITLE
Python SDK fails to install (Windows/cp1251)

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#370]
While following the Azure Getting Started guide for Windows/Python, I got an error while running `pip3 install -r requirements.txt`:

```
$ pip3 install -r requirements.txt
Requirement already satisfied: pulumi>=1.0.0 in c:\python36\lib\site-packages (from -r requirements.txt (line 1)) (1.1.0)
Collecting pulumi-azure>=1.0.0 (from -r requirements.txt (line 2))                                                                       
Using cached https://files.pythonhosted.org/packages/8f/76/1cf9e1e4e1e8d13222a34034d388fcb03d4d973f46cc1249e4caa9bb6bbf/pulumi_azure-1.0.0.tar.gz
ERROR: Command errored out with exit status 1:
command: 'c:\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shilk\\AppData\\Local\\Temp\\pip-install-p4ffcswp\\pulumi-azure\\setup.py'"'"'; __file__='"'"'C:\\Users\\shilk\\AppData\\Local\\Temp\\pip-install-p4ffcswp\\pulumi-azure\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
cwd: C:\Users\shilk\AppData\Local\Temp\pip-install-p4ffcswp\pulumi-azure\
Complete output (9 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "C:\Users\shilk\AppData\Local\Temp\pip-install-p4ffcswp\pulumi-azure\setup.py", line 33, in <module>
long_description=readme(),
File "C:\Users\shilk\AppData\Local\Temp\pip-install-p4ffcswp\pulumi-azure\setup.py", line 28, in readme
return f.read()
File "c:\python36\lib\encodings\cp1251.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1467: character maps to <undefined>
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Apparently, the `readme.rst` file contains symbols which have no meaning in the default codepage (CP1251 for me). We should change `setup.py` to read the file with explicit UTF8 encoding.

Doesn't happen for `pulumi-aws` for me, but I guess we should make the change across all repos.

**Comment by stack72** [comment]
Closed via #357 but not yet released

We will roll this out in a different manner with https://github.com/pulumi/pulumi-terraform/pull/494

**Comment by mikhailshilkov** [comment]
Ah, failed to find #356 somehow, mea culpa

**Comment by stack72** [comment]
@mikhailshilkov so did I until I looked at the CHANGELOG :D
