### ISSUE TITLE
Service Bus namespace not found on preview

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#416]
Any example with a Service Bus namespace and Azure Function bound to its objects (e.g. [this one](https://github.com/pulumi/pulumi-azure/tree/master/examples/topic)) fails on the initial `pulumi preview`:

```
Invoke of 'azure:servicebus/getNamespace:getNamespace' failed: rpc error: code = Unknown 
desc = invocation of azure:servicebus/getNamespace:getNamespace returned an error: 
invoking azure:servicebus/getNamespace:getNamespace: ServiceBus Namespace 
"test119dc73a" was not found in Resource Group "test9d682d52" ()
at deserializeResponse (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\runtime\invoke.js:317:15)
at invokeSyncWorker (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\runtime\invoke.js:208:25)
at invokeSync (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\runtime\invoke.js:101:12)
at Object.invoke (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\runtime\invoke.js:84:24)
at Object.getNamespace (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\servicebus\getNamespace.ts:36:65)
at ServiceBusFunction.pulumi.all.apply (C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\servicebus\zMixins.ts:328:37)
at C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\output.js:210:35         at Generator.next (<anonymous>)
at C:\work\pulumi\pulumi-azure\examples\topic\node_modules\@pulumi\azure\node_modules\@pulumi\pulumi\output.js:21:71          at new Promise (<anonymous>)

    (node:27904) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
```

**Comment by mikhailshilkov** [comment]
Downgrading the CLI from 1.6.0 to 1.5.2 solves the problem.

@pgavlin This seems to be related to the recent changes in the preview. [This line](https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/servicebus/zMixins.ts#L328) didn't use to be called during preview, and now it is. Anything we should do differently there?

**Comment by lukehoban** [comment]
@mikhailshilkov did we have coverage for this in either Azure or Examples tests?  Do you know why this didn’t trigger a test failure?

**Comment by mikhailshilkov** [comment]
@lukehoban  Yes, we do, that's how I found the issue. See [this build](https://travis-ci.com/pulumi/pulumi-azure/builds/137842228) for example.
