### ISSUE TITLE
Failed to retrieve the host keys

### ISSUE THREAD

**Issue by JonCanning** [pulumi/pulumi-azure#442]
When deploying an Azure Function using `ArchiveFunctionApp` we often get this error, and it can take repeated attempts at deployment to get it to succeed. I assume it is timing out waiting for the function to respond; is there anything we can do?

```
    error: Running program '/opt/atlassian/pipelines/agent/build/infrastructure' failed with an unhandled exception:
    Error: Failed to retrieve the host keys: {"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}],"Innererror":null}
        at FunctionApp.<anonymous> (/opt/atlassian/pipelines/agent/build/infrastructure/shared/node_modules/@pulumi/appservice/zMixins.ts:840:19)
        at Generator.next (<anonymous>)
        at fulfilled (/opt/atlassian/pipelines/agent/build/infrastructure/shared/node_modules/@pulumi/azure/appservice/zMixins.js:18:58)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by stack72** [comment]
Hi @JonCanning 

Have you tried adding a customTimeouts block?

e.g 

```
const x = new azure.core.ResourceGroup("my-example",{}, {
	customTimeouts: {
		create: "20m",
	}
});
```

I wrote this off my phone so apologies for the bad syntax 

Paul

**Comment by mikhailshilkov** [comment]
@stack72 If I recall correctly, custom timeouts aren't supported in the Azure provider

**Comment by mikhailshilkov** [comment]
I've heard about this issue before, but it's weird we don't hit it in our CI.
Anyway, we may need to consider adding retries to [here](https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/appservice/zMixins.ts#L838) similar to [this](https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/eventgrid/zMixins.ts#L147).

**Comment by CraftyFella** [comment]
I also have this same issue. It's made worse when there are multiple zip deployments in a single `pulumi up` I don't know how many deployments you're doing in the CI.. but in our deployments we have up to 10 functions being deployed.

**Comment by mikhailshilkov** [comment]
Thanks for highlighting this problem! As I mentioned above, the retry workaround should be fairly simple. I would love to see a community PR from one of you folks, otherwise, I'll take a look myself a bit later.

**Comment by CraftyFella** [comment]
I wish I could..

**Comment by CraftyFella** [comment]
Ok it's worth pointing out that @JonCanning and myself get this error when creating an EventGrid subscription with the following code:

```export const createEventSubscription = (
  name: string,
  topic: azure.eventgrid.Topic | string,
  eventTypes: string[],
  functionApp: azure.appservice.FunctionApp,
  storageAccount: azure.storage.Account,
  subjectFilter?: azure.types.input.eventgrid.EventSubscriptionSubjectFilter
) => {
  const topicId = (() => {
    if (topic instanceof azure.eventgrid.Topic) {
      return topic.id
    } else return topic
  })()
  const code = functionApp.getHostKeys().systemKeys.eventgrid_extension
  const url = pulumi.interpolate`https://${functionApp.defaultHostname}/runtime/webhooks/eventgrid?functionName=${name}&code=${code}`
  const deadLettersContainerName = name.toLowerCase() + '-deadletters'
  const deadLettersContainer = new azure.storage.Container(
    deadLettersContainerName,
    { name: deadLettersContainerName, storageAccountName: storageAccount.name }
  )
  new azure.eventgrid.EventSubscription(name, {
    scope: topicId,
    includedEventTypes: eventTypes,
    name: name,
    webhookEndpoint: { url: url },
    subjectFilter: subjectFilter,
    storageBlobDeadLetterDestination: {
      storageAccountId: storageAccount.id,
      storageBlobContainerName: deadLettersContainer.name
    }
  })
}```

**Comment by mikhailshilkov** [comment]
Another similar error that we are getting today is that the keys are retrieved successfully but they don't contain the `eventgrid_extension` one. Sounds like https://github.com/Azure/azure-functions-eventgrid-extension/issues/73. Looks like a good nudge to finally add the retries all over the place.

**Comment by CraftyFella** [comment]
We have a work around for this issue now.. instead of having functions triggered from EventGrid using the EventGridTrigger.. we push all events into storage queues and trigger off of those instead. It was trivial to do in pulumi.

E.g. 

```
export const createEventSubscriptionToStorageQueue = (
  name: string,
  topic: azure.eventgrid.Topic | string,
  eventTypes: string[],
  storageAccount: azure.storage.Account,
  subjectFilter?: azure.types.input.eventgrid.EventSubscriptionSubjectFilter
) => {
  const topicId = (() => {
    if (topic instanceof azure.eventgrid.Topic) {
      return topic.id
    } else return topic
  })()

  const inbox = createStorageQueue(storageAccount, name)
  createStorageQueue(storageAccount, `${name}-poison`)

  const deadLettersContainerName = name.toLowerCase() + '-deadletters'
  const deadLettersContainer = new azure.storage.Container(
    deadLettersContainerName,
    { name: deadLettersContainerName, storageAccountName: storageAccount.name }
  )

  return new azure.eventgrid.EventSubscription(name, {
    scope: topicId,
    includedEventTypes: eventTypes,
    name: name,
    subjectFilter: subjectFilter,
    storageQueueEndpoint: {
      queueName: inbox.name,
      storageAccountId: storageAccount.id
    },
    storageBlobDeadLetterDestination: {
      storageAccountId: storageAccount.id,
      storageBlobContainerName: deadLettersContainer.name
    }
  })
}
```

Might help another person who's getting this error while the pulumi team work on adding in the retries everywhere
