### ISSUE TITLE
Panic when creating an App Service with empty applicationLogs

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#454]
Running the initial creation of a stack with the following code

```ts
import * as azure from "@pulumi/azure";

const resourceGroup = new azure.core.ResourceGroup("play");

const appServicePlan = new azure.appservice.Plan("asp", {
    resourceGroupName: resourceGroup.name,
    kind: "App",
    sku: { tier: "Basic", size: "B1" },
});

const appWeb = new azure.appservice.AppService("app", {
    resourceGroupName: resourceGroup.name,
    appServicePlanId: appServicePlan.id,
    logs: {
        applicationLogs: {},
    },
});
```

fails with 

```
panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 108 [running]:
    github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure.ExpandAppServiceLogs(0x463d320, 0xc0009f4be0, 0x4, 0x463d320, 0xc0009f4be0, 0x1)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/terraform-provider-azurerm@v1.41.1-0.20200127185434-ab509a4a12de/azurerm/helpers/azure/app_service.go:1262 +0xc89
    github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/web.resourceArmAppServiceCreate(0xc0004c8fc0, 0x47885c0, 0xc0002c2800, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/terraform-provider-azurerm@v1.41.1-0.20200127185434-ab509a4a12de/azurerm/internal/services/web/resource_arm_app_service.go:300 +0x137f
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0009b2580, 0xc00089a640, 0xc001830a60, 0x47885c0, 0xc0002c2800, 0xc001830a01, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.1.1/helper/schema/resource.go:305 +0x365
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0009b2c00, 0xc00175b6f0, 0xc00089a640, 0xc001830a60, 0xc001830a60, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.1.1/helper/schema/provider.go:294 +0x99
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.(*Provider).Create(0xc0005b8300, 0x54da000, 0xc00081fec0, 0xc000eb5f00, 0xc0005b8300, 0x47daf01, 0xc00184c180)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.6.4/pkg/tfbridge/provider.go:645 +0x6be
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x54da000, 0xc00081fec0, 0x4ab72e0, 0xc000eb5f00, 0x4b1d720, 0x7fdf220, 0x54da000, 0xc00081fec0)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.9.1/sdk/proto/go/provider.pb.go:1615 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x54da000, 0xc00081fa40, 0x4ab72e0, 0xc000eb5f00, 0xc001830180, 0xc0018301a0, 0x0, 0x0, 0x544a340, 0xc0003f32f0)
    	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20171105060200-01f8541d5372/go/otgrpc/server.go:61 +0x36e
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x4b97260, 0xc0005b8300, 0x54da000, 0xc00081fa40, 0xc000eadb00, 0xc0001078c0, 0x54da000, 0xc00081fa40, 0xc00184a000, 0x1de)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.9.1/sdk/proto/go/provider.pb.go:1617 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e8160, 0x552c480, 0xc0005b8780, 0xc00183a800, 0xc0009be960, 0x7fb2170, 0x0, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x460
    google.golang.org/grpc.(*Server).handleStream(0xc0000e8160, 0x552c480, 0xc0005b8780, 0xc00183a800, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd97
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000a1d300, 0xc0000e8160, 0x552c480, 0xc0005b8780, 0xc00183a800)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xbb
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa1
```

The important bit is `applicationLogs: {},`.

Packages:

```
{
    "name": "typescript",
    "devDependencies": {
        "@types/node": "^8.0.0"
    },
    "dependencies": {
        "@pulumi/pulumi": "1.9.1",
        "@pulumi/azure": "1.12.0"
    }
}
```

This similar to #383 but the config is different and the error happens during creation, not update.

**Comment by mikhailshilkov** [comment]
Tried this today and the error doesn't repro anymore. I'll close as fixed.
