### ISSUE TITLE
Panic when creating a new kubernetes cluster in Go

### ISSUE THREAD

**Issue by tasiah** [pulumi/pulumi-azure#459]
I'm running `pulumi up` (and `dep ensure`) here: https://github.com/pulumi/examples/tree/tasiah/azure-go-aks/azure-go-aks. Everything runs successfully up until [Line 131 ](https://github.com/pulumi/examples/blob/tasiah/azure-go-aks/azure-go-aks/main.go#L131)in `main.go`, in which I get:
```bash
tasiahalim@Tasias-MacBook-Pro azure-go-aks % pulumi up
Previewing update (dev):

     Type                 Name              Plan     Info
     pulumi:pulumi:Stack  azure-go-aks-dev           1 error; 13 messages
 /vend
Diagnostics:
  pulumi:pulumi:Stack (azure-go-aks-dev):
    panic: reflect: Elem of invalid type
    goroutine 109 [running]:
    reflect.(*rtype).Elem(0x2379700, 0xc0001eeee0, 0x16)
    	/usr/local/go/src/reflect/type.go:921 +0x149
    github.com/pulumi/examples/azure-go-aks/vendor/github.com/pulumi/pulumi/sdk/go/pulumi.awaitInputs(0x27a7620, 0xc0000380a8, 0x2379780, 0xc0003b8c50, 0x94, 0x2379700, 0xc00000f990, 0x199, 0x27c1d00, 0x0, ...)
    	/Users/tasiahalim/go/src/github.com/pulumi/examples/azure-go-aks/vendor/github.com/pulumi/pulumi/sdk/go/pulumi/types.go:558 +0x18d7
    github.com/pulumi/examples/azure-go-aks/vendor/github.com/pulumi/pulumi/sdk/go/pulumi.awaitInputs(0x27a7620, 0xc0000380a8, 0x23f5880, 0xc0003b8c40, 0x99, 0x2397440, 0xc00000f980, 0x199, 0x22d3400, 0x0, ...)
    	/Users/tasiahalim/go/src/github.com/pulumi/examples/azure-go-aks/vendor/github.com/pulumi/pulumi/sdk/go/pulumi/types.go:592 +0xca2
    github.com/pulumi/examples/azure-go-aks/vendor/github.com/pulumi/pulumi/sdk/go/pulumi.ToOutputWithContext.func1(0x27c1d20, 0x2397440, 0x27a7620, 0xc0000380a8, 0x23f5880, 0xc0003b8c40, 0x27b1ce0, 0xc0003bc700)
    	/Users/tasiahalim/go/src/github.com/pulumi/examples/azure-go-aks/vendor/github.com/pulumi/pulumi/sdk/go/pulumi/types.go:671 +0x141
    created by github.com/pulumi/examples/azure-go-aks/vendor/github.com/pulumi/pulumi/sdk/go/pulumi.ToOutputWithContext
    	/Users/tasiahalim/go/src/github.com/pulumi/examples/azure-go-aks/vendor/github.com/pulumi/pulumi/sdk/go/pulumi/types.go:668 +0x1d2
    exit status 2
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```
I don't think this is a local configuration issue since I was able to run [`azure-cs-aks`](https://github.com/pulumi/examples/tree/tasiah/azure-go-aks/azure-cs-aks) fine.

**Comment by EvanBoyle** [comment]
So I've got a smaller repro of this issue.

The following code deploys just fine:

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/go/aws/kms"
	"github.com/pulumi/pulumi-aws/sdk/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		// Create a KMS Key for S3 server-side encryption
		key, err := kms.NewKey(ctx, "my-key", nil)
		if err != nil {
			return err
		}

		// Create an AWS resource (S3 Bucket)
		bucket, err := s3.NewBucket(ctx, "my-bucket", &s3.BucketArgs{
			ServerSideEncryptionConfiguration: s3.BucketServerSideEncryptionConfigurationArgs{
				Rule: s3.BucketServerSideEncryptionConfigurationRuleArgs{
					ApplyServerSideEncryptionByDefault: s3.BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefaultArgs{
						SseAlgorithm:   pulumi.StringInput(pulumi.String("aws:kms")),
						KmsMasterKeyId: key.ID(),
					},
				},
			},
		})
		if err != nil {
			return err
		}

		// Export the name of the bucket
		ctx.Export("bucketName", bucket.ID())
		return nil
	})
}

```

But if you pass a pointer to the `rule` field you get the same panic:

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/go/aws/kms"
	"github.com/pulumi/pulumi-aws/sdk/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		// Create a KMS Key for S3 server-side encryption
		key, err := kms.NewKey(ctx, "my-key", nil)
		if err != nil {
			return err
		}

		// Create an AWS resource (S3 Bucket)
		bucket, err := s3.NewBucket(ctx, "my-bucket", &s3.BucketArgs{
			ServerSideEncryptionConfiguration: s3.BucketServerSideEncryptionConfigurationArgs{
				Rule: &s3.BucketServerSideEncryptionConfigurationRuleArgs{
					ApplyServerSideEncryptionByDefault: s3.BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefaultArgs{
						SseAlgorithm:   pulumi.StringInput(pulumi.String("aws:kms")),
						KmsMasterKeyId: key.ID(),
					},
				},
			},
		})
		if err != nil {
			return err
		}

		// Export the name of the bucket
		ctx.Export("bucketName", bucket.ID())
		return nil
	})
}
```

**Comment by EvanBoyle** [comment]
A little more experimenting shows that this trips if you try to pass a pointer to any property that has a pulumi annotation in the model such as `pulumi:"rule"`

**Comment by tasiah** [comment]
Evan found a "workaround" to this issue at pulumi/examples#577. This is a "workaround" (in quotes) because I'm not quite sure how moving the `&` around fixes anything: https://github.com/pulumi/examples/commit/f990fc8eee5c49def448f4b289bc8cef4b7e005e#diff-caeadd9f21f74e23f3e025c0fdd3e620.

**Comment by EvanBoyle** [comment]
There's a bug in the marshaling code that needs to be fixed (fails with pointers but works with direct references).  Avoiding passing pointers bypasses this. 

This issue still needs to be fixed, but the workaround should unblock you for now.
