### ISSUE TITLE
using `azure.core.getSubscriptions()` without any parameters throws an error

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi-azure#465]
Hi,

When we use `azure.core.getSubscriptions()` without any parameters, we get the following error:

```
Diagnostics:
  pulumi:pulumi:Stack (...):
    error: Running program '/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam' failed with an unhandled exception:
    AssertionError: Failure: Decoder hit an error
        at new goog.asserts.AssertionError (/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam/node_modules/google-protobuf/google-protobuf.js:81:876)
        at Object.goog.asserts.fail (/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam/node_modules/google-protobuf/google-protobuf.js:84:89)
        at jspb.BinaryReader.nextField (/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam/node_modules/google-protobuf/google-protobuf.js:375:123)
        at proto.google.protobuf.Struct.deserializeBinaryFromReader (/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam/node_modules/google-protobuf/google/protobuf/struct_pb.js:146:17)
        at jspb.BinaryReader.readMessage (/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam/node_modules/google-protobuf/google-protobuf.js:384:329)
        at proto.google.protobuf.Value.deserializeBinaryFromReader (/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam/node_modules/google-protobuf/google/protobuf/struct_pb.js:338:14)
        at jspb.BinaryReader.readMessage (/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam/node_modules/google-protobuf/google-protobuf.js:384:329)
        at proto.google.protobuf.ListValue.deserializeBinaryFromReader (/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam/node_modules/google-protobuf/google/protobuf/struct_pb.js:719:14)
        at jspb.BinaryReader.readMessage (/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam/node_modules/google-protobuf/google-protobuf.js:384:329)
        at proto.google.protobuf.Value.deserializeBinaryFromReader (/Users/manu/workspaces/maif/azure-iac/foundations-base/foundations-iam/node_modules/google-protobuf/google/protobuf/struct_pb.js:343:14)
```

But, if we add the `displayNamePrefix` property, it returns some subscriptions as expected.

```ts
const subscriptions = azure.core.getSubscriptions( { displayNamePrefix: "Sub"})
```

**Comment by stack72** [comment]
Hi @boillodmanuel 

So I just tried this with the following code:

```
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";

const subscriptions = azure.core.getSubscriptions()

export const subs = subscriptions.subscriptions;
```

I was able to get the correct subscriptions back for azure:

```
▶ pulumi up --yes --skip-preview
Updating (dev):
     Type                 Name           Status
 +   pulumi:pulumi:Stack  subs-test-dev  created

Outputs:
    subs: [
        [0]: {
            displayName        : "<redacted>"
            locationPlacementId: "Public_2014-09-01"
            quotaId            : "Sponsored_2016-01-01"
            spendingLimit      : "Off"
            state              : "Enabled"
            subscriptionId     : "<redacted>"
            tenantId           : "<redacted>"
        }
        [1]: {
            displayName        : "<redacted>"
            locationPlacementId: "Public_2014-09-01"
            quotaId            : "PayAsYouGo_2014-09-01"
            spendingLimit      : "Off"
            state              : "Disabled"
            subscriptionId     : "<redacted>
            tenantId           : "<redacted>"
        }
    ]

Resources:
    + 1 created

Duration: 13s

Permalink: https://app.pulumi.com/stack72/subs-test/dev/updates/1
```

I am using Pulumi 1.11.0 and Pulumi.Azure 1.14.0

Thoughts?

**Comment by boillodmanuel** [comment]
I updated my pulumi version to `1.11.1` and can reproduce the error.

## `azure.core.getSubscriptions()`

with 
```ts
azure.core.getSubscriptions()
```

I get the error. 
Running with `pulumi up --logtostderr --debug --verbose=9` produce the following debug file: https://gist.github.com/boillodmanuel/b2beb0e1eda6243b38d92ae8214f1b21


## azure.core.getSubscriptions({displayNamePrefix: "Archi"})

with 
```ts
azure.core.getSubscriptions({displayNamePrefix: "Archi"})
```

I get NO error and it returns several subscriptions.

Running with `pulumi up --logtostderr --debug --verbose=9` produce the following debug file: https://gist.github.com/boillodmanuel/25f4d4a100606c8d3eff2acb2d0ee36b

## Analysis

I don't know why I get this error, especially as the ("rpc?") payload returned contains the 34 subscriptions in both case??

**Comment by stack72** [comment]
@boillodmanuel just checking back in on this - is this still the issue with 2.0? I still can't recreate it :/

**Comment by boillodmanuel** [comment]
Tried with
```
        "@pulumi/azure": "^2.1.0",
        "@pulumi/pulumi": "^1.12.1"
```

It works now! Great

**Comment by stack72** [comment]
nice - thanks @boillodmanuel 

Sorry that took so long to get back to you

**Comment by boillodmanuel** [comment]
I only get some issue to follow. But not you 😅

Le jeu. 26 mars 2020 à 17:14, Paul Stack <notifications@github.com> a
écrit :
