### ISSUE TITLE
Panic when trying to retrieve existing resource with a different provider

### ISSUE THREAD

**Issue by elsesiy** [pulumi/pulumi-azure#470]
I'm trying to get the existing resource state using a different than the default provider.

```
	peerProvider, err := azure.NewProvider(ctx, "peering-provider", &azure.ProviderArgs{
		SubscriptionId: pulumi.String("<subscription-id>"),
	})
	if err != nil {
		return nil, err
	}

	test, err := network.GetVirtualNetwork(ctx, "test,", pulumi.ID("/subscriptions/<subscription-id>/resourceGroups/<rg>/providers/Microsoft.Network/virtualNetworks/<vnet-name>"), nil, pulumi.Provider(peerProvider))

```

This snippet above errors out with:
```
    panic: reflect: call of reflect.Value.Type on zero Value
    goroutine 114 [running]:
    reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
    	/usr/local/Cellar/go/1.14/libexec/src/reflect/value.go:1872 +0x183
    github.com/pulumi/pulumi/sdk/go/pulumi.marshalInputs(0x2fc0060, 0x0, 0x2b, 0x0, 0xc00054e370, 0xc0003ae000, 0x61, 0x0, 0x0)
    	/Users/jelsesiy/Developer/cloudeng/k8s-pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/go/pulumi/rpc.go:76 +0x18a
    github.com/pulumi/pulumi/sdk/go/pulumi.(*Context).prepareResourceInputs(0xc000274000, 0x2fc0060, 0x0, 0x2eb74e7, 0x2b, 0xc00054e370, 0xc000383100, 0x0, 0x0, 0x0)
    	/Users/jelsesiy/Developer/cloudeng/k8s-pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/go/pulumi/context.go:710 +0x23a
    github.com/pulumi/pulumi/sdk/go/pulumi.(*Context).ReadResource.func1(0xc000383100, 0xc000274000, 0x2fd1d20, 0x2fac630, 0x2fc0060, 0x0, 0x2eb74e7, 0x2b, 0xc00054e370, 0x2e97fff, ...)
    	/Users/jelsesiy/Developer/cloudeng/k8s-pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/go/pulumi/context.go:315 +0x252
    created by github.com/pulumi/pulumi/sdk/go/pulumi.(*Context).ReadResource
    	/Users/jelsesiy/Developer/cloudeng/k8s-pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/go/pulumi/context.go:298 +0x3b1
    exit status 2
```

Debug info:
```
$ go version
go version go1.14 darwin/amd64

$ pulumi version
v1.11.1

$ pulumi plugin ls

NAME     KIND      VERSION  SIZE    INSTALLED   LAST USED
azure    resource  1.14.0   160 MB  1 week ago  1 week ago
azuread  resource  1.5.0    39 MB   2 days ago  2 days ago
random   resource  1.5.0    36 MB   2 days ago  2 days ago
tls      resource  1.4.0    36 MB   3 days ago  3 days ago
```

Related to https://github.com/pulumi/pulumi-azure/issues/461

**Comment by EvanBoyle** [comment]
Thanks for reporting, I'll take a look.

**Comment by EvanBoyle** [comment]
@elsesiy so you don't have to wait until the next release on Wednesday, you can work around this issue temporarily by replacing your fourth argument of `nil` with `&core.ResourceGroupState{}`

```go
test, err := network.GetVirtualNetwork(ctx, "test,", pulumi.ID("/subscriptions/<subscription-id>/resourceGroups/<rg>/providers/Microsoft.Network/virtualNetworks/<vnet-name>"), &core.ResourceGroupState{}, pulumi.Provider(peerProvider))
```
