### ISSUE TITLE
Getting certificate with azure.keyvault.getSecret fails on deserialization

### ISSUE THREAD

**Issue by yohanb** [pulumi/pulumi-azure#472]
When executing the following code:

`const wildcardCertificate = azure.keyvault.getSecret({
    name: "foobar-wildcard",
    keyVaultId: data.keyVaultId,
});`

`const wildcardCertificatePassword = azure.keyvault.getSecret({
    name: "foobar-wildcard-password",
    keyVaultId: data.keyVaultId,
});`

I get the following error:

`Diagnostics:
  pulumi:pulumi:Stack (***):
    error: Running program '/Users/yohan.belval/git/***/src/pulumi' failed with an unhandled exception:
    AssertionError: Failure: Invalid wire type: 6 (at position 20)
        at new goog.asserts.AssertionError (/Users/yohan.belval/git/***/src/pulumi/node_modules/google-protobuf/google-protobuf.js:81:876)
        at Object.goog.asserts.fail (/Users/yohan.belval/git/***/src/pulumi/node_modules/google-protobuf/google-protobuf.js:84:89)
        at jspb.BinaryReader.nextField (/Users/yohan.belval/git/***/src/pulumi/node_modules/google-protobuf/google-protobuf.js:375:536)
        at Function.jspb.Map.deserializeBinary (/Users/yohan.belval/git/***/src/pulumi/node_modules/google-protobuf/google-protobuf.js:411:59)
        at /Users/yohan.belval/git/***/src/pulumi/node_modules/google-protobuf/google/protobuf/struct_pb.js:155:18
        at jspb.BinaryReader.readMessage (/Users/yohan.belval/git/***/src/pulumi/node_modules/google-protobuf/google-protobuf.js:384:329)
        at proto.google.protobuf.Struct.deserializeBinaryFromReader (/Users/yohan.belval/git/***/src/pulumi/node_modules/google-protobuf/google/protobuf/struct_pb.js:154:14)
        at jspb.BinaryReader.readMessage (/Users/yohan.belval/git/***/src/pulumi/node_modules/google-protobuf/google-protobuf.js:384:329)
        at Function.proto.pulumirpc.InvokeResponse.deserializeBinaryFromReader (/Users/yohan.belval/git/***/src/pulumi/node_modules/@pulumi/pulumi/proto/provider_pb.js:1072:14)
        at Function.proto.pulumirpc.InvokeResponse.deserializeBinary (/Users/yohan.belval/git/***/src/pulumi/node_modules/@pulumi/pulumi/proto/provider_pb.js:1052:41)`

**Comment by stack72** [comment]
Hi @yohanb 

Please can you tell me what version of pulumi and pulumi-azure you are using here?

Thanks

Paul

**Comment by yohanb** [comment]
Hi @stack72 ,
```
"@pulumi/azure": "^1.14.0",
"@pulumi/pulumi": "^1.0.0"
```
As for the CLI, `v1.11.1`

**Comment by stack72** [comment]
Thanks @yohanb 

I will try and see if I can recreate this

P.

**Comment by yohanb** [comment]
It seems to only happen when I get the a certificate value and then some other secret value.
Getting only the certificate doesn't throw an exception.  Seems the state is somehow corrupted first by the deserialization of the certificate and then fails for the subsequent secrets.

**Comment by mikhailshilkov** [comment]
I'll take the liberty to close this out as no-repro. The issue doesn't have code for us to try it out, it's been three years without comments or upvotes, so I don't think it's actionable.
