### ISSUE TITLE
NetworkSecurityGroupSecurityRule missing in .NET API

### ISSUE THREAD

**Issue by zakaluka** [pulumi/pulumi-azure#507]
`NetworkSecurityGroupSecurityRule` does not appear to exist in the .NET API (C# or F#).  This causes `pulumi up` to fail with the following message:

```
Diagnostics:
  pulumi:pulumi:Stack (c19-pulumi-dev):
    error: Running program '/home/zakaluka/projects/c19-pulumi/bin/Debug/netcoreapp3.1/c19-pulumi.dll' failed with an unhandled exception:
    System.InvalidOperationException: Pulumi.Azure.Network.Outputs.NetworkSecurityGroupSecurityRules is not a supported argument type.
    	monitor.registerResourceOutputs(...).c19_nsg_waf.SecurityRules.id[0]
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Serialization.Serializer.SerializeListAsync(String ctx, IList list)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

EDIT: To be clear, I created the resources using `NetworkSecurityRule` outside of the `NetworkSecurityGroup`.  This error is thrown on running `pulumi up`, when it is trying to update internal state (I assume).

**Comment by mikhailshilkov** [comment]
Hi @zakaluka do you have a code snippet that I could use to reproduce? Thanks!

**Comment by zakaluka** [comment]
Here is some code in F#:

First, I created an NSG with 1 Rule:

```fsharp
  /// Build NSG for WAF
  let c19_nsg_waf =
    let name = "c19-nsg-waf"
    NetworkSecurityGroup
      (t name,
       NetworkSecurityGroupArgs
         (Name = i2 name, ResourceGroupName = io C19Automation.Name,
          Tags = tags ManagementSecurity))

  /// Add NSG Rule to allow Inbound traffic on ports 80 and 443.
  let c19_nsgrule_in_valid_internet =
    let name = "c19-nsgrule-in-valid-internet"
    NetworkSecurityRule
      (t name,
       NetworkSecurityRuleArgs
         (Name = i2 name,
          Description = input "Allow inbound traffic from the Internet",
          Access = input "Allow", Direction = input "Inbound",
          SourceAddressPrefix = input "*", SourcePortRanges = validPorts,
          DestinationAddressPrefix = io c19_ip.IpAddress,
          DestinationPortRanges = validPorts,
          NetworkSecurityGroupName = io c19_nsg_waf.Name, Priority = input 100,
          Protocol = input "Tcp", ResourceGroupName = io C19Automation.Name))
```

Then, I added 1 more entry, which caused the failure during refresh:

```fsharp
  let c19_nsgrule_out_all =
    let name = "c19-nsgrule-in-invalid"
    NetworkSecurityRule
      (t name,
       NetworkSecurityRuleArgs
         (Name = i2 name,
          Description = input "Deny outbound traffic to the Internet",
          Access = input "Deny", Direction = input "Outbound",
          SourceAddressPrefix = input "VirtualNetwork",
          SourcePortRange = input "*",
          DestinationAddressPrefix = input "Internet",
          DestinationPortRange = input "*",
          NetworkSecurityGroupName = io c19_nsg_waf.Name, Priority = input 101,
          Protocol = input "*", ResourceGroupName = io C19Automation.Name))
```

**Comment by zakaluka** [comment]
Here is an easier snippet, maybe.  It uses inline Security Rules instead of separate ones that reference the NSG.  Just adding  one rule causes failure here.  All items are created successfully, but the state update on Pulumi is what seems to be failing (I tore down the entire environment and re-built it using the script, and everything succeeded on Azure but failure happened during state update).

```fsharp
  let c19_nsg_waf =
    let name = "c19-nsg-waf"
    let nsrInbound = "c19-nsgrule-in-valid-internet"
    let nsrOutbound = "c19-nsgrule-in-invalid"
    NetworkSecurityGroup
      (t name,
       NetworkSecurityGroupArgs
         (Name = i2 name, ResourceGroupName = io C19Automation.Name,
          Tags = tags ManagementSecurity,
          SecurityRules =
            ([ NetworkSecurityGroupSecurityRulesArgs
                 (Name = i2 nsrInbound,
                  Description = input "Allow inbound traffic from the Internet",
                  Access = input "Allow", Direction = input "Inbound",
                  SourceAddressPrefix = input "*", SourcePortRanges = validPorts,
                  DestinationAddressPrefix = io c19_ip.IpAddress,
                  DestinationPortRanges = validPorts, Priority = input 100,
                  Protocol = input "Tcp") ]
             |> List.map input
             |> inputList)))
```

Output:
```
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember): 
Previewing update (dev):
     Type                                   Name                             Plan       Info
     pulumi:pulumi:Stack                    c19-pulumi-dev                          1 error
     ├─ azure:core:ResourceGroup            C19Automation-track-2                   
 ~   ├─ azure:network:NetworkSecurityGroup  c19-nsg-waf-track-2              update     [diff: ~securityRules]
     ├─ azure:network:Subnet                c19-subnet-waf-frontend-track-2             [diff: -delegations,serviceEndpoints]
     ├─ azure:network:PublicIp              c19-ip-track-2                              
     └─ azure:network:VirtualNetwork        c19-vnet-track-2                            [diff: -dnsServers,subnets]
 
Diagnostics:
  pulumi:pulumi:Stack (c19-pulumi-dev):
    error: Running program '/home/zakaluka/projects/c19-pulumi/bin/Debug/netcoreapp3.1/c19-pulumi.dll' failed with an unhandled exception:
    System.InvalidOperationException: Pulumi.Azure.Network.Outputs.NetworkSecurityGroupSecurityRules is not a supported argument type.
    	monitor.registerResourceOutputs(...).c19_nsg_waf.SecurityRules.id[0]
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Serialization.Serializer.SerializeListAsync(String ctx, IList list)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

**Comment by mikhailshilkov** [comment]
Hi @zakaluka 

I tried to repro this issue but it all works fine so far. I'm clearly not doing something the same way you do.

Here is the gist with my full code: https://gist.github.com/mikhailshilkov/fb45df272c235a2643398df5bd102998

I tried creating and NSG with 1 rule, then adding another one, then removing, as internal property or as separate resources, all worked fine.

Could you give my repro a try and log the example commands you execute in the console to get an error?

I'm on Pulumi v. 1.14.1, just in case. Thank you!

**Comment by mikhailshilkov** [comment]
Nevermind, I've finally dig into the error message. I suppose you export the rules as stack outputs, something like thig:

```fs
dict [("test", c19_nsg_waf.SecurityRules :> obj)]
```

This is not currently supported, see https://github.com/pulumi/pulumi/issues/3641

**Comment by sachinshahredmane** [comment]
@mikhailshilkov Thank you for digging into this.  Is there documentation somewhere that states what objects/items can or cannot be exported?

**Comment by zakaluka** [comment]
@mikhailshilkov Thank you for digging into this. Is there documentation somewhere that states what objects/items can or cannot be exported?

**Comment by mikhailshilkov** [comment]
Not really, you were supposed to hit this error but something didn't quite work:

> Allowed types are:  String, Boolean, Int32, Double, Nullable<...>, ImmutableArray<...> and ImmutableDictionary<string, ...>

https://github.com/pulumi/pulumi/blob/6e15c83e1a2bce2e99841eebd0786106a9d51377/sdk/dotnet/Pulumi/Serialization/Converter.cs#L381

**Comment by zakaluka** [comment]
Thank you.  Closing this for now, as I have the answer.  If there's any work you'd like to track against this issue, please feel free to reopen it.
