### ISSUE TITLE
Memory Address Error When Updating Disabled Subscription

### ISSUE THREAD

**Issue by d0ctajones** [pulumi/pulumi-azure#531]
Hello,

It looks like there's a bug in `pulumi-azure` where if you're trying to `pulumi up` to update an existing disabled subscription it will fail like so (debug log):
```
2020-04-21T00:11:08.4573081Z     pulumi:pulumi:Stack self_service-***** running debug: {"error":{"code":"ReadOnlyDisabledSubscription",
"message":"The subscription '*****' is disabled and therefore marked as read only. You cannot perform any write actions
on this subscription until it is re-enabled."}}
2020-04-21T00:11:08.4604084Z     pulumi:pulumi:Stack self_service-***** running panic: runtime error: invalid memory address or nil pointer dereference
2020-04-21T00:11:08.4605280Z     pulumi:pulumi:Stack self_service-***** running [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x34cd36f]
2020-04-21T00:11:08.4606250Z     pulumi:pulumi:Stack self_service-***** running goroutine 60 [running]:
2020-04-21T00:11:08.4607437Z     pulumi:pulumi:Stack self_service-***** running github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm.retryVnetPeeringsClientCreateUpdate.func1(0x0)
2020-04-21T00:11:08.4608940Z     pulumi:pulumi:Stack self_service-***** running         /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_network_peering.go:234 +0x2cf
2020-04-21T00:11:08.4610351Z     pulumi:pulumi:Stack self_service-***** running github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource.Retry.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2020-04-21T00:11:08.4612221Z     pulumi:pulumi:Stack self_service-***** running         /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/wait.go:22 +0x4e
2020-04-21T00:11:08.4613881Z     pulumi:pulumi:Stack self_service-***** running github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1(0xc00055af60, 0xc0004bec40, 0xc000c5ae00, 0xc000ab4840, 0xc000056050, 0xc000705ff8)
2020-04-21T00:11:08.4615374Z     pulumi:pulumi:Stack self_service-***** running         /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/state.go:103 +0x292
2020-04-21T00:11:08.4616689Z     pulumi:pulumi:Stack self_service-***** running created by github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
2020-04-21T00:11:08.4618004Z     pulumi:pulumi:Stack self_service-***** running         /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/state.go:80 +0x1bf
```
Failing is definitely correct if the subscription is read-only. However, It should probably be gracefully handled by Pulumi and let the user know that it failed for this exact reason instead of a stacktrace

Here are the tool versions:
```
pulumi = "~=1.8.1"
pulumi-azure = "~=1.4.0"
pulumi-kubernetes = "~=1.4.2"
pulumi-azuread = "~=1.4.0"
pulumi-random = "~=1.4.0"
```
CLI version `1.6.1`

**Comment by leezen** [comment]
Thanks for the report. Any chance you're able to reproduce this on more recent versions of the CLI and SDK?

**Comment by stack72** [comment]
Going to close this since there has been no activity on it since 2020
