### ISSUE TITLE
'assertion failed' on pulumi destroy

### ISSUE THREAD

**Issue by mhixon449** [pulumi/pulumi-azure#622]
Pulumi appears to throw a stack trace while attempting to refresh the state in Azure China:

This seems to be a one-off, as other pulumi destroy jobs work as expected.

```2020-06-25T19:50:25.4427376Z ##[section]Starting: Run Pulumi
2020-06-25T19:50:25.4432739Z ==============================================================================
2020-06-25T19:50:25.4433148Z Task         : Shell++
2020-06-25T19:50:25.4433446Z Description  : Execute bash script
2020-06-25T19:50:25.4433759Z Version      : 0.3.1
2020-06-25T19:50:25.4434047Z Author       : ms-devlabs
2020-06-25T19:50:25.4434476Z Help         : [More Information](https://github.com/openalm/Extension-UtilitiesPack)
2020-06-25T19:50:25.4434996Z ==============================================================================
2020-06-25T19:50:25.5649435Z 
2020-06-25T19:50:25.5649972Z container_name=pulumi-devops-lib
2020-06-25T19:50:25.5650183Z 
2020-06-25T19:50:25.5651106Z docker run --name ${container_name} -e CONFIG --env-file /home/vsts/work/r1/a/.envfile -d ***/pulumi:$(git rev-parse HEAD) -c 'while true; do sleep 86400; done'
2020-06-25T19:50:25.5651546Z 
2020-06-25T19:50:25.5651820Z docker exec ${container_name} make bootstrap
2020-06-25T19:50:25.5652082Z 
2020-06-25T19:50:25.5652548Z docker exec ${container_name} bash -c "echo $CONFIG"
2020-06-25T19:50:25.5652797Z 
2020-06-25T19:50:25.5653364Z docker exec -w /root/idca_pulumi/programs/self_service ${container_name} pipenv install
2020-06-25T19:50:25.5653658Z 
2020-06-25T19:50:25.5654332Z docker exec -w /root/idca_pulumi/programs/self_service ${container_name} pipenv run pulumi stack init cn-intcne2-smruleset
2020-06-25T19:50:25.5654701Z 
2020-06-25T19:50:25.5655673Z docker exec -w /root/idca_pulumi/programs/self_service ${container_name} pipenv run pulumi up --non-interactive --yes --stack cn-intcne2-smruleset
2020-06-25T19:50:25.5670104Z [command]/bin/bash /home/vsts/work/r1/a/_idca-pulumi-modules/scripts/self_service_pipeline.sh --fqin cn-intcne2-smruleset --commit 44bf4e2485fb68ede83164806bb5f9724fbd32d5 --envfile /home/vsts/work/r1/a/.envfile --action destroy --fallback-tag latest --tier environment
2020-06-25T19:50:25.5748145Z Default Working Directory = /home/vsts/work/r1/a
2020-06-25T19:50:27.9303971Z 44bf4e2485fb68ede83164806bb5f9724fbd32d5: Pulling from pulumi
2020-06-25T19:50:27.9306201Z fc7181108d40: Pulling fs layer
2020-06-25T19:50:27.9306565Z 01f3b6f74410: Pulling fs layer
2020-06-25T19:50:27.9307013Z 163142c4383b: Pulling fs layer
2020-06-25T19:50:27.9307363Z eeed0da1db91: Pulling fs layer
2020-06-25T19:50:27.9307921Z ea6d6fd23371: Pulling fs layer
2020-06-25T19:50:27.9308260Z aa81013f854a: Pulling fs layer
2020-06-25T19:50:27.9310525Z 65198dad08b9: Pulling fs layer
2020-06-25T19:50:27.9310877Z 564e40b24b96: Pulling fs layer
2020-06-25T19:50:27.9311608Z 8007ec9c1b93: Pulling fs layer
2020-06-25T19:50:27.9312081Z f2d6c7952e84: Pulling fs layer
2020-06-25T19:50:27.9312405Z d3629c827463: Pulling fs layer
2020-06-25T19:50:27.9312868Z 95f7c21e00ad: Pulling fs layer
2020-06-25T19:50:27.9313472Z 65198dad08b9: Waiting
2020-06-25T19:50:27.9315635Z 564e40b24b96: Waiting
2020-06-25T19:50:27.9319725Z 8007ec9c1b93: Waiting
2020-06-25T19:50:27.9320052Z f2d6c7952e84: Waiting
2020-06-25T19:50:27.9320370Z d3629c827463: Waiting
2020-06-25T19:50:27.9320685Z 95f7c21e00ad: Waiting
2020-06-25T19:50:27.9320966Z eeed0da1db91: Waiting
2020-06-25T19:50:27.9321259Z ea6d6fd23371: Waiting
2020-06-25T19:50:27.9321554Z aa81013f854a: Waiting
2020-06-25T19:50:29.2721044Z 01f3b6f74410: Verifying Checksum
2020-06-25T19:50:29.2721782Z 01f3b6f74410: Download complete
2020-06-25T19:50:29.8221814Z eeed0da1db91: Verifying Checksum
2020-06-25T19:50:29.8222875Z eeed0da1db91: Download complete
2020-06-25T19:50:34.6906187Z ea6d6fd23371: Verifying Checksum
2020-06-25T19:50:34.6907207Z ea6d6fd23371: Download complete
2020-06-25T19:50:40.6005865Z fc7181108d40: Verifying Checksum
2020-06-25T19:50:40.6013081Z fc7181108d40: Download complete
2020-06-25T19:50:41.5823452Z fc7181108d40: Pull complete
2020-06-25T19:50:41.7539860Z 01f3b6f74410: Pull complete
2020-06-25T19:50:46.0935018Z 65198dad08b9: Verifying Checksum
2020-06-25T19:50:46.0935601Z 65198dad08b9: Download complete
2020-06-25T19:50:46.4671823Z 163142c4383b: Download complete
2020-06-25T19:50:47.3075756Z 163142c4383b: Pull complete
2020-06-25T19:50:47.3740098Z eeed0da1db91: Pull complete
2020-06-25T19:50:47.6076724Z ea6d6fd23371: Pull complete
2020-06-25T19:50:48.6577603Z aa81013f854a: Verifying Checksum
2020-06-25T19:50:48.6578118Z aa81013f854a: Download complete
2020-06-25T19:50:48.6819692Z 564e40b24b96: Verifying Checksum
2020-06-25T19:50:48.6820101Z 564e40b24b96: Download complete
2020-06-25T19:50:48.7856071Z aa81013f854a: Pull complete
2020-06-25T19:50:48.9740975Z f2d6c7952e84: Verifying Checksum
2020-06-25T19:50:48.9741434Z f2d6c7952e84: Download complete
2020-06-25T19:50:49.9060944Z 65198dad08b9: Pull complete
2020-06-25T19:50:50.4595261Z 95f7c21e00ad: Verifying Checksum
2020-06-25T19:50:50.4595685Z 95f7c21e00ad: Download complete
2020-06-25T19:50:51.0500714Z 564e40b24b96: Pull complete
2020-06-25T19:51:15.3260339Z 8007ec9c1b93: Verifying Checksum
2020-06-25T19:51:15.3260858Z 8007ec9c1b93: Download complete
2020-06-25T19:51:15.7712449Z 8007ec9c1b93: Pull complete
2020-06-25T19:51:15.8459286Z f2d6c7952e84: Pull complete
2020-06-25T19:55:54.9641628Z d3629c827463: Verifying Checksum
2020-06-25T19:55:54.9643366Z d3629c827463: Download complete
2020-06-25T19:56:08.8540762Z d3629c827463: Pull complete
2020-06-25T19:56:09.0139409Z 95f7c21e00ad: Pull complete
2020-06-25T19:56:09.0167956Z Digest: sha256:af28c28c309a425b8abbc9918c94b9fc32cdfb932d3a2c71ce4d99f5238a1103
2020-06-25T19:56:09.0192111Z Status: Downloaded newer image for ***/pulumi:44bf4e2485fb68ede83164806bb5f9724fbd32d5
2020-06-25T19:56:09.0204988Z ***/pulumi:44bf4e2485fb68ede83164806bb5f9724fbd32d5
2020-06-25T19:56:15.2183669Z ae96446b40186c65cc045ecbe22e6659c38f767c9b89daf906e35afc3b3dff1a
2020-06-25T19:56:16.2534462Z PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.pulumi/bin:/root/.pandoc/bin:/root/.pulumi/plugins
2020-06-25T19:56:16.2536368Z HOSTNAME=ae96446b4018
2020-06-25T19:56:16.2537081Z PULUMI_ACCESS_TOKEN=***
2020-06-25T19:56:16.2537546Z TIER=environment
2020-06-25T19:56:16.2548320Z CONFIG={"vnet_range": "10.88.168.0/23", "node_size": "Standard_D4s_v3", "node_count": "3", "max_node_count": "6", "subscription_access_policy": [{"assignee": "e60abcf9-589b-499e-bb65-d9d4b9777d8e", "role_id": "acdd72a7-3385-48ef-bd42-f606fba81ae7"}, {"assignee": "0159d7cd-b0b6-44af-be76-582abd83fc0e", "role_id": "8e3af657-a8ff-443c-a75c-2fe8c4bcb635"}, {"assignee": "0fbad6a5-e958-4c87-a6ff-fdf755e02ce4", "role_id": "51c2b546-c920-4e8f-b818-614d798d64a9"}], "resource_access_policy": [{"assignee": "0159d7cd-b0b6-44af-be76-582abd83fc0e", "role_id": "8e3af657-a8ff-443c-a75c-2fe8c4bcb635"}, {"assignee": "0fbad6a5-e958-4c87-a6ff-fdf755e02ce4", "role_id": "51c2b546-c920-4e8f-b818-614d798d64a9"}], "subscription": "86332384-1b72-4d46-a0c3-a0146b098868", "admin_user": "daimlerAdmin", "k8s_version": "1.14.8", "ssh_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSSASLpefF40bTohrvY3jALFX+IeTsfPIhYoMhZjML3s46P3XdbSz9yjNrlDwMLHh0ncBJ/RN704uNiQDaCnmYUeKyypWgDx+8DQOamrTeOjqkQxezpxjJII4R34kj/dhiINgWfyr/72xZN9XPaIHcmwPWBRLbX5p6U3zHoJpGx45OKxlpuCI2K49vU5vCARQW0mKKRZDMrfIG+c9wXdDkXqARaM69jDVxhJQ/F1/8BphQxgVk3tUsQst849CjUwRzPDIoG6T9GLUbksp45Fgg+9DSgmKd+muT/SuxjS5gTl2huEaM721VAOOPrznRABYIX5/sTvcA35+SD8GkmVmj", "vm_ssh_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSSASLpefF40bTohrvY3jALFX+IeTsfPIhYoMhZjML3s46P3XdbSz9yjNrlDwMLHh0ncBJ/RN704uNiQDaCnmYUeKyypWgDx+8DQOamrTeOjqkQxezpxjJII4R34kj/dhiINgWfyr/72xZN9XPaIHcmwPWBRLbX5p6U3zHoJpGx45OKxlpuCI2K49vU5vCARQW0mKKRZDMrfIG+c9wXdDkXqARaM69jDVxhJQ/F1/8BphQxgVk3tUsQst849CjUwRzPDIoG6T9GLUbksp45Fgg+9DSgmKd+muT/SuxjS5gTl2huEaM721VAOOPrznRABYIX5/sTvcA35+SD8GkmVmj", "laworkspace_pricing_tier": "PerGB2018", "laworkspace_name": "cn-intcne2-smruleset-laworkspace", "rbac_enabled": "True", "apim_pricing_tier": "Developer", "apim_scale_units": "1", "tags": {"mic_creator": "PSTX_a_SUBUKKA@corpdir.partner.onmschina.cn", "mic_created": "2020-01-30T22:58:44+00:00", "mic_expires": "Never"}, "tenant_id": "***", "azure_cloud": "AzureChinaCloud", "location": "chinaeast2", "geo": "cn", "region": "cne2", "munich_vpn_psk": "", "envname": "cn-intcne2-smruleset", "parentname": "cn-intcne2", "parent_tier": "site", "parent_subscription": "2fe8ab1b-19a3-4ffc-bbaf-4ac2a6f19202", "parent_vnet_rg_name": "cn-intcne2-site-rg", "parent_vnet_name": "cn-intcne2-vnet", "parent_vnet_id": "/subscriptions/2fe8ab1b-19a3-4ffc-bbaf-4ac2a6f19202/resourceGroups/cn-intcne2-site-rg/providers/Microsoft.Network/virtualNetworks/cn-intcne2-vnet"}
2020-06-25T19:56:16.2556965Z SP_PREFIX=DAI-C_CA6_
2020-06-25T19:56:16.2560541Z ARM_CLIENT_ID=***
2020-06-25T19:56:16.2561317Z ARM_CLIENT_SECRET=***
2020-06-25T19:56:16.2561968Z ARM_TENANT_ID=***
2020-06-25T19:56:16.2562596Z ARM_SUBSCRIPTION_ID=86332384-1b72-4d46-a0c3-a0146b098868
2020-06-25T19:56:16.2562998Z ARM_ENVIRONMENT=china
2020-06-25T19:56:16.2563628Z azure_client_id=***
2020-06-25T19:56:16.2564276Z azure_client_secret=***
2020-06-25T19:56:16.2564913Z azure_tenant_id=***
2020-06-25T19:56:16.2565561Z azure_subscription_id=86332384-1b72-4d46-a0c3-a0146b098868
2020-06-25T19:56:16.2566268Z AZ_CLIENT_ID=***
2020-06-25T19:56:16.2566887Z AZ_CLIENT_SECRET=***
2020-06-25T19:56:16.2567503Z AZ_TENANT_ID=***
2020-06-25T19:56:16.2568115Z AZ_SUBSCRIPTION_ID=86332384-1b72-4d46-a0c3-a0146b098868
2020-06-25T19:56:16.2568813Z CLIENT_APP_ID=***
2020-06-25T19:56:16.2569430Z SERVER_APP_ID=***
2020-06-25T19:56:16.2569812Z SERVER_APP_SECRET=***
2020-06-25T19:56:16.2570417Z TENANT_ID=***
2020-06-25T19:56:16.2571034Z TF_VAR_client_id=***
2020-06-25T19:56:16.2571682Z TF_VAR_client_secret=***
2020-06-25T19:56:16.2572324Z TF_VAR_tenant_id=***
2020-06-25T19:56:16.2572989Z TF_VAR_azure_client_id=***
2020-06-25T19:56:16.2573684Z TF_VAR_azure_client_secret=***
2020-06-25T19:56:16.2574367Z TF_VAR_azure_tenant_id=***
2020-06-25T19:56:16.2575257Z TF_VAR_subscription_id=86332384-1b72-4d46-a0c3-a0146b098868
2020-06-25T19:56:16.2575661Z PULUMI_IMPORT=
2020-06-25T19:56:16.2576009Z IDCA_PULUMI_KEY=***
2020-06-25T19:56:16.2576547Z TERRAFORM_BACKEND_ACCESS_KEY=***
2020-06-25T19:56:16.2576879Z VAULT_SKIP_VERIFY=true
2020-06-25T19:56:16.2577372Z LANG=C.UTF-8
2020-06-25T19:56:16.2577740Z GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
2020-06-25T19:56:16.2578118Z PYTHON_VERSION=3.7.3
2020-06-25T19:56:16.2578441Z PYTHON_PIP_VERSION=19.1.1
2020-06-25T19:56:16.2578763Z PYTHONUNBUFFERED=TRUE
2020-06-25T19:56:16.2579088Z PULUMI_SKIP_UPDATE_CHECK=TRUE
2020-06-25T19:56:16.2580136Z ADO_PIP_AUTH=https://idca:***@pkgs.dev.azure.com/daimler-mic/_packaging/idca/pypi/simple/
2020-06-25T19:56:16.2580643Z HOME=/root
2020-06-25T19:56:16.2581017Z Logging in using access token from PULUMI_ACCESS_TOKEN
2020-06-25T19:56:16.4030343Z error: stack 'cn-intcne2-smruleset-env' already exists
2020-06-25T19:56:17.0975453Z Previewing update (daimler-mic/cn-intcne2-smruleset-env):
2020-06-25T19:56:19.2537557Z 
2020-06-25T19:56:20.8046347Z     pulumi:pulumi:Stack self_service-cn-intcne2-smruleset-env  To sign in, use a web browser to open the page https://microsoft.com/deviceloginchina and enter the code DYJEYWQNP to authenticate.
2020-06-25T19:56:21.9559839Z     pulumi:pulumi:Stack self_service-cn-intcne2-smruleset-env  warning: Using generated kubernetes service principal values
2020-06-25T19:56:25.2575676Z     pulumi:pulumi:Stack self_service-cn-intcne2-smruleset-env running warning: Using generated kubernetes service principal values
2020-06-25T19:56:25.2693392Z     idca:modules:environment:Environment cn-intcne2-smruleset  
2020-06-25T19:56:25.3269826Z     idca:modules:cluster:KubernetesCluster cn-intcne2-smruleset  
2020-06-25T19:56:25.4107211Z     pulumi:providers:azure cn-intcne2-smruleset-parent-provider  
2020-06-25T19:56:25.4125917Z     azure:core:ResourceGroup cn-intcne2-smruleset-rg  
2020-06-25T19:56:25.4133074Z     idca:modules:service_principal:ServicePrincipal cn-intcne2-smruleset-sp  
2020-06-25T19:56:25.4133798Z     azure:core:ResourceGroup cn-intcne2-smruleset-k8s-rg  
2020-06-25T19:56:25.5600669Z     azuread:index:Application DAI-C_CA6_cn-intcne2-smruleset-sp  
2020-06-25T19:56:25.5642281Z     azure:network:VirtualNetwork cn-intcne2-smruleset-vnet  
2020-06-25T19:56:25.5663472Z     azure:network:RouteTable cn-intcne2-smruleset-envrt  
2020-06-25T19:56:25.5697781Z panic: fatal: An assertion has failed
2020-06-25T19:56:25.5698115Z 
2020-06-25T19:56:25.5698399Z goroutine 563 [running]:
2020-06-25T19:56:25.5698831Z github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
2020-06-25T19:56:25.5699379Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
2020-06-25T19:56:25.5699917Z github.com/pulumi/pulumi/pkg/util/contract.Assert(...)
2020-06-25T19:56:25.5700459Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26
2020-06-25T19:56:25.5701199Z github.com/pulumi/pulumi/pkg/resource/deploy.NewSameStep(0xc001127da0, 0x7ffbc9580b60, 0xc0014a2f10, 0xc00023af00, 0xc001456a00, 0x0, 0x0)
2020-06-25T19:56:25.5701930Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step.go:75 +0x6f8
2020-06-25T19:56:25.5702741Z github.com/pulumi/pulumi/pkg/resource/deploy.(*stepGenerator).generateSteps(0xc0011b46c0, 0x7ffbc9580b60, 0xc0014a2f10, 0xc0011c6180, 0x3, 0xc00057baa0, 0x1, 0xc0011c6180)
2020-06-25T19:56:25.5703582Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_generator.go:454 +0x10da
2020-06-25T19:56:25.5704424Z github.com/pulumi/pulumi/pkg/resource/deploy.(*stepGenerator).GenerateSteps(0xc0011b46c0, 0x7ffbc9580b60, 0xc0014a2f10, 0x7ffbc9580b60, 0xc0014a2f10, 0x1, 0xc00057bac0, 0x45d9c0)
2020-06-25T19:56:25.5705275Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_generator.go:155 +0x5a
2020-06-25T19:56:25.5706006Z github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).handleSingleEvent(0xc00118cf40, 0x198a1a0, 0xc0014a2f10, 0x0, 0x1)
2020-06-25T19:56:25.5706837Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:361 +0x138
2020-06-25T19:56:25.5707720Z github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).Execute.func3(0xc001191260, 0xc00118cf40, 0xc00114d140, 0x19b5860, 0xc0011b2880, 0xc00118b260, 0x0, 0x19b5920, 0xc00118afc0, 0x0, ...)
2020-06-25T19:56:25.5708612Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:235 +0x210
2020-06-25T19:56:25.5709433Z github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).Execute(0xc00118cf40, 0x19b5920, 0xc00118afc0, 0x19b5c60, 0xc0011b4360, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, ...)
2020-06-25T19:56:25.5710251Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:251 +0x7da
2020-06-25T19:56:25.5710844Z github.com/pulumi/pulumi/pkg/resource/deploy.(*Plan).Execute(...)
2020-06-25T19:56:25.5711614Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:335
2020-06-25T19:56:25.5712384Z github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk.func1(0x19b5c60, 0xc0011b4360, 0xc0011b4240, 0x19b5920, 0xc00118afc0, 0xc00118af01, 0xc00114cef0, 0xc001190ba0)
2020-06-25T19:56:25.5713158Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/plan.go:192 +0x24a
2020-06-25T19:56:25.5713708Z created by github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk
2020-06-25T19:56:25.5714262Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/plan.go:178 +0x177
2020-06-25T19:56:26.2097321Z Previewing destroy (daimler-mic/cn-intcne2-smruleset-env):
2020-06-25T19:56:28.4682708Z 
2020-06-25T19:56:28.4688418Z  ~  pulumi:pulumi:Stack self_service-cn-intcne2-smruleset-env refreshing 
2020-06-25T19:56:28.4689674Z  ~  pulumi:pulumi:Stack self_service-cn-intcne2-smruleset-env refreshing 
2020-06-25T19:56:28.4690827Z  ~  idca:modules:cluster:KubernetesCluster cn-intcne2-smruleset refreshing 
2020-06-25T19:56:28.4691929Z  ~  idca:modules:cluster:KubernetesCluster cn-intcne2-smruleset refresh 
2020-06-25T19:56:28.4693341Z  ~  idca:modules:environment:Environment cn-intcne2-smruleset refreshing 
2020-06-25T19:56:28.4694380Z  ~  idca:modules:environment:Environment cn-intcne2-smruleset refresh 
2020-06-25T19:56:28.4695669Z  ~  azure:core:ResourceGroup cn-intcne2-smruleset-rg refreshing 
2020-06-25T19:56:28.4700225Z  ~  azure:core:ResourceGroup cn-intcne2-smruleset-k8s-rg refreshing 
2020-06-25T19:56:28.4701731Z  ~  idca:modules:service_principal:ServicePrincipal cn-intcne2-smruleset-sp refreshing 
2020-06-25T19:56:28.4702870Z  ~  azure:network:VirtualNetwork cn-intcne2-smruleset-vnet refreshing 
2020-06-25T19:56:28.4704091Z  ~  idca:modules:service_principal:ServicePrincipal cn-intcne2-smruleset-sp refresh 
2020-06-25T19:56:28.4705181Z  ~  pulumi:providers:azure cn-intcne2-smruleset-parent-provider refreshing 
2020-06-25T19:56:28.4706437Z  ~  pulumi:providers:azure cn-intcne2-smruleset-parent-provider refresh 
2020-06-25T19:56:28.4712110Z  ~  azure:network:RouteTable cn-intcne2-smruleset-envrt refreshing 
2020-06-25T19:56:28.4712979Z  ~  azure:network:VirtualNetworkPeering peer-cn-intcne2-to-cn-intcne2-smruleset refreshing 
2020-06-25T19:56:28.4713668Z  ~  azuread:index:Application DAI-C_CA6_cn-intcne2-smruleset-sp refreshing 
2020-06-25T19:56:28.4749657Z panic: fatal: An assertion has failed
2020-06-25T19:56:28.4754457Z 
2020-06-25T19:56:28.4762860Z goroutine 568 [running]:
2020-06-25T19:56:28.4763326Z github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
2020-06-25T19:56:28.4763799Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
2020-06-25T19:56:28.4764318Z github.com/pulumi/pulumi/pkg/util/contract.Assert(...)
2020-06-25T19:56:28.4767577Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26
2020-06-25T19:56:28.4777216Z github.com/pulumi/pulumi/pkg/resource/plugin.(*provider).Read(0xc001046300, 0xc0000a2300, 0x100, 0x0, 0x0, 0xc0003ecf90, 0xc0003ecfc0, 0x0, 0x7fffffff, 0x100, ...)
2020-06-25T19:56:28.4778136Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/plugin/provider_plugin.go:668 +0xfcb
2020-06-25T19:56:28.4779004Z github.com/pulumi/pulumi/pkg/resource/deploy.(*RefreshStep).Apply(0xc00118a700, 0x1, 0x16e1f06, 0x23, 0xc000cdde18, 0x3)
2020-06-25T19:56:28.4779977Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step.go:726 +0x140
2020-06-25T19:56:28.4780539Z github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).executeStep(0xc00111b500, 0xf, 0x19cf0a0, 0xc00118a700, 0x28, 0x8)
2020-06-25T19:56:28.4781105Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:271 +0x217
2020-06-25T19:56:28.4781657Z github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).executeChain(0xc00111b500, 0xf, 0xc0011ef780, 0x1, 0x1)
2020-06-25T19:56:28.4782208Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:221 +0xe6
2020-06-25T19:56:28.4782958Z github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).worker.func1(0xc00111b500, 0xf, 0xc0011ef780, 0x1, 0x1, 0xc0011823c0)
2020-06-25T19:56:28.4783528Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:371 +0xea
2020-06-25T19:56:28.4784012Z created by github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).worker
2020-06-25T19:56:28.4784499Z 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:368 +0x2fa
2020-06-25T19:56:28.5129980Z /bin/bash failed with return code: 2
2020-06-25T19:56:28.5143431Z return code: 1
2020-06-25T19:56:28.5160681Z ##[section]Finishing: Run Pulumi```

**Comment by mikhailshilkov** [comment]
I don't really know how to repro this. Since this issue is 3+ years old, I'll close it as not actionable.
