### ISSUE TITLE
Cryptic error when providing invalid AppSettings for AppService

### ISSUE THREAD

**Issue by nathanwinder-perficient** [pulumi/pulumi-azure#761]
I accidentally left an empty app setting `{"", ""}` in my code but got a cryptic error that didn't help identify the issue:

```csharp
new Pulumi.Azure.AppService.AppService(NameFormatter.AppServiceName(name), new AppServiceArgs
            {
                ResourceGroupName = resourceGroupName,
                AppServicePlanId = plan.Id,
                AppSettings = new InputMap<string>
                {
                    { "ASPNETCORE_ENVIRONMENT", _deployment.Environment },
                    { "WEBSITE_RUN_FROM_PACKAGE", codeBlobUrl },
                    { "", "" }
                }
            });
```

```
 panic: fatal: An assertion has failed
    goroutine 794 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/go/common/util/contract/assert.go:26
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*conversionContext).MakeTerraformInputs(0xc0018bb320, 0x0, 0xc0009d7230, 0x0, 0x0, 0x0, 0x9c00000000000001, 0x9709900, 0x1, 0xc)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfbridge/schema.go:301 +0x7a1
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*conversionContext).MakeTerraformInput(0xc0018bb320, 0xc001f6fce0, 0xc, 0x0, 0x0, 0x4e2ca60, 0xc0009d7230, 0x5c69460, 0xc0010ec780, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfbridge/schema.go:256 +0xe4c
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*conversionContext).MakeTerraformInputs(0xc0018bb320, 0xc0009d71a0, 0xc0009d71d0, 0x5bb1be0, 0xc000a96480, 0xc00068b500, 0x40d400, 0x20, 0x4c07a20, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfbridge/schema.go:309 +0x1f9
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformInputs(0xc0018bb300, 0xc00095e930, 0xc0009d71a0, 0xc0009d71d0, 0x5bb1be0, 0xc000a96480, 0xc00068b500, 0xc001b99650, 0x403ce1, 0x4fe5480, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfbridge/schema.go:138 +0xcf
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Check(0xc0000021e0, 0x5b97060, 0xc0009d7080, 0xc000c34100, 0xc0000021e0, 0x4ab3201, 0xc000c34380)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfbridge/provider.go:619 +0x6b6
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Check_Handler.func1(0x5b97060, 0xc0009d7080, 0x4e487c0, 0xc000c34100, 0x4ea7fa0, 0x9707c40, 0x5b97060, 0xc0009d7080)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/proto/go/provider.pb.go:2208 +0x8d
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x5b97060, 0xc0009d6f60, 0x4e487c0, 0xc000c34100, 0xc0018bb100, 0xc0018bb120, 0x0, 0x0, 0x5b17040, 0xc000090fb0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f2
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Check_Handler(0x4f7a980, 0xc0000021e0, 0x5b97060, 0xc0009d6f60, 0xc00007b080, 0xc000617be0, 0x5b97060, 0xc0009d6f60, 0xc001352000, 0x27b)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/proto/go/provider.pb.go:2210 +0x152
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00094e1c0, 0x5bdf480, 0xc000528780, 0xc001885400, 0xc001167110, 0x96c78b8, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x511
    google.golang.org/grpc.(*Server).handleStream(0xc00094e1c0, 0x5bdf480, 0xc000528780, 0xc001885400, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xcd4
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000a80050, 0xc00094e1c0, 0x5bdf480, 0xc000528780, 0xc001885400)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa8
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x20b
```

**Comment by mikhailshilkov** [comment]
Still reproduces, a full repro below. Moving to the bridge according to the panic.

```
using System;
using System.Threading.Tasks;
using Pulumi;
using Pulumi.Azure.AppService;
using Pulumi.Azure.AppService.Inputs;
using Pulumi.Azure.Core;

return await Deployment.RunAsync(() =>
{
    var resourceGroup = new ResourceGroup("test",new ResourceGroupArgs());


    var plan = new Plan("test", new PlanArgs {
        ResourceGroupName = resourceGroup.Name,
        Kind = "App",
        Sku = new PlanSkuArgs
        {
            Tier = "Basic",
            Size = "B1",
        },
    });

    new AppService("test", new AppServiceArgs
            {
                ResourceGroupName = resourceGroup.Name,
                AppServicePlanId = plan.Id,
                AppSettings = new InputMap<string>
                {
                    { "ASPNETCORE_ENVIRONMENT", "_deployment.Environment" },
                    { "WEBSITE_RUN_FROM_PACKAGE", "codeBlobUrl" },
                    { "", "" }
                }
            });
    return Task.CompletedTask;
});
```
