### ISSUE TITLE
azure.netapp.Volume: Expected 'list' got '<class 'str'>'

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi-azure#888]
Hi,
I would like to deploy a NetApp volume:
```python
import pulumi_azure as azure

rg = azure.core.ResourceGroup(
    "zzz_rg",
    name = "zzzzz",
    location = "westeurope",
)

vnet = azure.network.VirtualNetwork(
    "vnet",
    resource_group_name=rg.name,
    location=rg.location,
    address_spaces=["10.0.0.0/16"],
)

vnet_default = azure.network.Subnet(
    "vnet_default",
    name="default",
    virtual_network_name=vnet.name,
    resource_group_name=vnet.resource_group_name,
    address_prefixes=["10.0.1.0/24"]
)

vnet_netapp = azure.network.Subnet(
    "vnet_netapp",
    name="netapp",
    virtual_network_name=vnet.name,
    resource_group_name=vnet.resource_group_name,
    address_prefixes=["10.0.2.0/24"],
    delegations=[
        azure.network.SubnetDelegationArgs(
            name="anf",
            service_delegation=azure.network.SubnetDelegationServiceDelegationArgs(
                name="Microsoft.Netapp/volumes",
            ),
        ),
    ],
)

anf_account = azure.netapp.Account(
    "anf_account",
    name="account",
    resource_group_name=rg.name,
    location=rg.location,
)

anf_pool = azure.netapp.Pool(
    "anf_pool",
    name="netapp-pool",
    account_name=anf_account.name,
    resource_group_name=anf_account.resource_group_name,
    location=anf_account.location,
    service_level="Standard",
    size_in_tb=4,
)

anf_vol = azure.netapp.Volume(
    "anf_vol",
    name="vol",
    account_name=anf_account.name,
    pool_name=anf_pool.name,
    resource_group_name=anf_account.resource_group_name,
    location=anf_account.location,
    protocols=["NFSv3"],
    volume_path="vol",
    service_level=anf_pool.service_level,
    storage_quota_in_gb=1024,
    subnet_id=vnet_netapp.id,
    export_policy_rules=[
        azure.netapp.VolumeExportPolicyRuleArgs(
            rule_index=1,
            protocols_enabled=["NFSv3"],
            allowed_clients=vnet_default.address_prefixes,
            unix_read_only=False,
            unix_read_write=True,
            root_access_enabled=True,
        ),
    ],
)
```
This is the output:
```console
$ pulumi preview
Previewing update (dev):
     Type                             Name            Plan       Info
 +   pulumi:pulumi:Stack              cyclecloud-dev  create     3 errors
 +   ├─ azure:core:ResourceGroup      zzz_rg          create
 +   ├─ azure:network:VirtualNetwork  vnet            create
 +   ├─ azure:netapp:Account          anf_account     create
 +   ├─ azure:network:Subnet          vnet_default    create
 +   ├─ azure:network:Subnet          vnet_netapp     create
 +   └─ azure:netapp:Pool             anf_pool        create

Diagnostics:
  pulumi:pulumi:Stack (cyclecloud-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 45, in run_pulumi_func
        await wait_for_rpcs()
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 94, in wait_for_rpcs
        raise exception
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/usr/lib/python3.9/site-packages/pulumi/output.py", line 91, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.9/site-packages/pulumi/output.py", line 91, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/lib/python3.9/site-packages/pulumi/output.py", line 91, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 14 more times]
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 438, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 100, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, translate, typ)
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 121, in serialize_properties
        result = await serialize_property(v, deps, input_transformer, get_type(k))
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 164, in serialize_property
        props.append(await serialize_property(elem, deps, input_transformer, element_type))
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 274, in serialize_property
        return {
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 275, in <dictcomp>
        k: await serialize_property(v, deps, input_transformer, types.get(k))
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 161, in serialize_property
        element_type = _get_list_element_type(typ)
      File "/usr/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 79, in _get_list_element_type
        raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
    AssertionError: Unexpected type. Expected 'list' got '<class 'str'>'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Any advice on to setup `allowed_clients`?

Thanks

**Comment by yellowhat** [comment]
May bad it is `protocols_enabled="NFSv3"` not `protocols_enabled=["NFSv3"]`
